shiny/_static.py
=> Fix directory creation for shinylive assets

.github/workflows/pytest.yaml
This removes no-longer-necessary deploy keys.
=> Simplify GHA workflow

shiny/_static.py
=> Avoid opening temporary file twice

CHANGELOG.md, shiny/render/_render.py, shiny/session/_session.py
=> Avoid automatically namespaced input read in render.plot

examples/ui-func/app.py, shiny/_app.py, shiny/_main.py
=> Allow app UI to be provided as a function

.github/workflows/pytest.yaml
https://github.com/actions/checkout/releases
https://github.com/actions/setup-python/releases
https://github.com/pypa/gh-action-pypi-publish/releases
=> Upgrade GitHub Actions

README.md
Small addition that completes the instructions on how to start development on the project.
=> Improved contribution instructions in `README.md`

shiny/examples/input_action_button/app.py, shiny/examples/input_action_link/app.py
Fixes #380
We'll need to redeploy the website after this (or does that happen automatically?)
=> Fix broken examples

e2e/conftest.py
The version I removed didn't know not to use ports considered by browsers to be unsafe
=> Eliminate duplicate random_port logic

.github/py-shiny/setup/action.yaml, .github/shiny/checkout-and-install/action.yaml, .github/workflows/pytest.yaml, Makefile, e2e/conftest.py, e2e/controls.py, e2e/examples/test_examples.py, e2e/inputs/test_input_slider.py, examples/airmass/location.py, examples/brownian/shinymediapipe/_hand.py, examples/moduleapp/app.py, pytest.ini, setup.cfg, shiny/examples/render_image/app.py, shiny/examples/update_checkbox_group/app.py
=> Add tests to check that all examples do not display errors

.github/py-shiny/setup/action.yaml, .github/workflows/pytest.yaml
=> Add GHA step ID so followup steps are not skipped

.github/workflows/pytest.yaml, shiny/examples/update_checkbox_group/app.py, shiny/ui/_input_check_radio.py, shiny/ui/_input_update.py
=> Add `tuple[str, ...]` support to input radio and checkbox group

README.md
This creates a slightly better README file, and adds links to the Discord.
=> Add small description, Discord link

shiny/experimental/ui/__init__.py, shiny/experimental/ui/_fill.py
=> fix: Use a single class for Filling Layout protocol

shiny/experimental/examples/as_fill_item/app.py, shiny/experimental/examples/as_fillable_container/app.py, shiny/experimental/examples/layout_sidebar/app.py, shiny/experimental/ui/_card.py, shiny/experimental/ui/_fill.py, shiny/experimental/ui/_layout.py, shiny/experimental/ui/_navs.py, shiny/experimental/ui/_output.py, shiny/experimental/ui/_page.py, shiny/experimental/ui/_sidebar.py, shiny/experimental/ui/_valuebox.py
This makes sure that the `fill.css` HTML dependency is always added when fill components are used in an app.
=> Make sure fill dependency is added

examples/penguins/app.py, shiny/experimental/e2e/accordion/app.py, shiny/experimental/examples/accordion_panel_remove/app.py, shiny/experimental/ui/_navs.py, shiny/experimental/ui/_sidebar.py, shiny/ui/_navs.py
* Fix bad app logic
* Make sure all layouts are `.tagify()`ed in `NavSet`s
* Related: #338 
* Add a `tagify()` method to `Sidebar`, but throw a `NotImplementedError`
* Use shinyswatch in penguins demo
* Remove custom height of 90px
* Fixes: https://github.com/rstudio/py-shiny/issues/563
=> fix: bugs found during QA testing

examples/penguins/app.py, shiny/experimental/e2e/accordion/app.py, shiny/experimental/e2e/sidebar/data.py, shiny/experimental/examples/accordion_panel_remove/app.py, shiny/experimental/ui/_navs.py, shiny/experimental/ui/_sidebar.py, shiny/ui/_navs.py
=> fix: small bugs found during QA

shiny/experimental/ui/__init__.py, shiny/experimental/ui/_accordion.py, shiny/experimental/ui/_card.py, shiny/experimental/ui/_css_unit.py, shiny/experimental/ui/_fill.py, shiny/experimental/ui/_layout.py, shiny/experimental/ui/_navs.py, shiny/experimental/ui/_output.py, shiny/experimental/ui/_page.py, shiny/experimental/ui/_sidebar.py, shiny/experimental/ui/_valuebox.py, shiny/ui/_x/_css_unit.py, shiny/ui/_x/_sidebar.py
Also:
* fix: `validate_css_*()` -> `as_css_*()`
=> docs(x): Missing docs for classes and methods

examples/duckdb/app.py, examples/duckdb/manifest.json, examples/duckdb/query.py, examples/duckdb/requirements.txt, setup.cfg
This creates a duckdb query app which illustrates on disk data integration, modules, and inserting/removing UIs.
=> Duckdb example

Makefile, setup.cfg
```
(shiny) $ make coverage
coverage run --source shiny -m pytest
make: coverage: No such file or directory
make: *** [coverage] Error 1
```
(note reports zero coverage, and only running the non-e2e tests):
```
(shiny) $ make coverage               
coverage run --source shiny -m pytest
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.10.8, pytest-7.4.0, pluggy-1.3.0
rootdir: /Users/diana/workspace/py-shiny
configfile: pytest.ini
testpaths: tests/pytest/
plugins: anyio-4.0.0, rerunfailures-12.0, playwright-0.4.2, timeout-2.1.0, asyncio-0.21.1, base-url-2.0.0, syrupy-4.4.0, xdist-3.3.1
asyncio: mode=strict
8 workers [84 items] …
```
=> Fix make coverage

tests/e2e/bugs/0666-sidebar/app.py, tests/e2e/bugs/0666-sidebar/test_sidebar_colors.py, tests/e2e/controls.py
Add a check to verify position of sidebar
=> Finish todo task for sidebar test

shiny/quarto.py
If a Quarto Shiny app has `from x import *` in a regular code block (not a `context: setup` one), then it will throw an error because the code gets copied into the app.py server function like this:
```py
def server(input, output, session):
from x import *
```
It will print out this error at app run time:
```
SyntaxError: import * only allowed at module level
```
With this change, we walk the AST looking for `import *` and if we find one, it throws an error at write time, instead of at app run time:
```
'import *' statements cannot be used in a regular Shiny code block in Quarto.
Please move '*' imports to a code block with '#| context: setup', or used named imports instead.
```
=> For quarto apps, check for `import *`

shiny/ui/_page.py
=> Fix bug in fillable_mobile logic

shiny/express/ui/_cm_components.py
=> Express version of `panel_conditional()` should treat condition argument as a positional arg

examples/cpuinfo/app.py, shiny/reactive/_reactives.py, tests/pytest/test_renderer.py
=> fix: Do not allow for renderer's to be given to reactive effects

tests/playwright/deploys/apps/plotly_app/app.py
=> chore: Remove experimental from app

examples/express/shared.py, examples/express/shared_app.py
=> Fix `examples/express/shared_app.py`

.github/py-shiny/setup/action.yaml, .github/workflows/verify-js-built.yaml, Makefile, setup.cfg, shiny/_app.py, shiny/_autoreload.py, shiny/_main.py, shiny/express/ui/_hold.py, shiny/input_handler.py, shiny/render/_coordmap.py, shiny/render/_express.py, shiny/render/_render.py, shiny/render/_try_render_plot.py, shiny/session/_session.py, shiny/ui/_sidebar.py, tests/playwright/controls.py, tests/playwright/examples/example_apps.py, tests/pytest/test_display_decorator.py, tests/pytest/test_output_transformer.py, tests/pytest/test_reactives.py, tests/pytest/test_renderer.py, tests/pytest/test_sidebar.py
Related:
* https://github.com/microsoft/pyright/pull/7073 : `reportRedeclaration`
* https://github.com/microsoft/pyright/pull/7075 : `reportAttributeAccessIssue `
* https://github.com/microsoft/pyright/pull/7077 : `reportArgumentType `, `reportReturnType`
=> chore: Fix pyright 1.1.348 updates

setup.cfg
This addresses https://github.com/posit-dev/py-shiny/issues/1114#issuecomment-1942757757.
=> Un-pin starlette and add python-multipart requirement

tests/playwright/shiny/bugs/0648-update-slider-datetime-value/test_update_slider_datetime_value.py
Followup of #1142
Adds a tz to the end of the datetime
=> chore: Fix test from #1142

shiny/api-examples/input_dark_mode/app-core.py, shiny/api-examples/input_dark_mode/app-express.py, shiny/ui/_input_dark_mode.py
=> `update_dark_mode()` now sends it's message synchronously

tests/playwright/shiny/components/nav/app.py, tests/playwright/shiny/components/nav/test_nav.py
Updated tests/playwright/shiny/components/nav/test_nav.py to loop and soft assert
=> test: Consolidate playwright nav component test

tests/playwright/conftest.py
Also remove timeout on cleanup
=> test: Retry making a new shiny app proc if port is busy

.github/workflows/build-docs.yaml
This PR builds shinylive and deploys it to github pages along with the API docs.
=> Build shinylive for Github pages

Makefile
=> chore(deploys): Only test on chrome browser by default

tests/playwright/shiny/deprecated/output_transformer/test_output_transformer_example.py, tests/playwright/shiny/server/output_transformer/test_output_transformer_async.py
Unskip the tests after fixing them locally. Skipping them right now till they are fixed.
=> Skip flaky playwright tests

examples/model-score/app.py, tests/playwright/shiny/components/nav/app.py
https://github.com/posit-dev/py-shiny/actions/runs/8975211477/job/24649305569#step:7:2746
=> Attempt to fix playwright tests

shiny/ui/_navs.py, tests/pytest/test_navs.py
This will hopefully make the `tests/playwright/shiny/components/nav/test_nav.py` less flaky
=> Make navset id more robust to collisions

tests/playwright/controls.py, tests/playwright/shiny/components/data_frame/edit/app.py, tests/playwright/shiny/components/data_frame/html_columns_df/df_organization/app.py, tests/playwright/shiny/components/data_frame/html_columns_df/df_organization/test_df_organization.py, tests/playwright/shiny/components/data_frame/html_columns_df/tabbing/app.py, tests/playwright/shiny/components/data_frame/html_columns_df/tabbing/test_tabbing.py, tests/playwright/shiny/components/data_frame/html_columns_df/test_html_columns.py
Add tests for the dataframe filtering and sorting methods.
In addition, also add method to Dataframe controls that allows users to select single or multiple rows.
=> tests: Add dataframe filtering and sorting tests

shiny/render/_data_frame.py
=> bug(data frame): Use `<ID>_data_view_rows`

setup.cfg
=> chore(deps): Add `prompt-toolkit` as direct dependency

shiny/ui/_chat.py
=> Avoid using `run_coro_sync()` to append initial `Chat(messages)`

.github/py-shiny/setup/action.yaml, shiny/api-examples/data_frame_styles/app-core.py, shiny/api-examples/data_frame_styles/app-express.py, shiny/render/_data_frame_utils/_datagridtable.py, shiny/render/_data_frame_utils/_styles.py, shiny/render/_data_frame_utils/_types.py, tests/playwright/shiny/components/data_frame/styles/app.py, tests/playwright/shiny/components/data_frame/styles/test_df_styles.py, tests/playwright/shiny/components/data_frame/styles_class/app.py, tests/playwright/shiny/components/data_frame/styles_class/test_df_styles_class.py
If there's only one option, then it shouldn't be required.
cc @cpsievert
=> feat(data frame styles): Allow style "location" to not be required

CHANGELOG.md, shiny/_utils.py, shiny/http_staticfiles.py
=> Fix #1601: Force text/javascript for .js files

.github/workflows/deploy-tests.yaml, tests/playwright/deploys/express-page_sidebar/test_deploys_express_page_sidebar.py
Add the env vars for the shinyapps.io deploy tests in the workflow file
=> fix(tests): Add missing env vars for shinyapps.io tests

Makefile
Related: https://github.com/narwhals-dev/narwhals/pull/1161#pullrequestreview-2362069032
=> ci(narwhals): Add type, format, and lint tests for narwhals

pyproject.toml
* https://github.com/narwhals-dev/narwhals/pull/1186
=> chore: Use narwhals >= 1.10.0

README.md
https://shiny.posit.co/py/docs/install.html - > https://shiny.posit.co/py/docs/install-create-run.html
=> README: fix broken installation link

tests/pytest/test_render_data_frame_tbl_data.py
* Generalize to allow for ending with `*Type`
=> bug: Fix narwhals test covering new `NestedType`

shiny/ui/_chat.py
Fixes a newly surfaced overlapping overloads error that was revealed with pyright 1.1.394.
=> fix(pyright): Fix overlapping overloads

CHANGELOG.md
Just consolidates and re-orders a few items in `CHANGELOG.md`
=> Prep changelog for release

pyproject.toml
Related: https://github.com/microsoft/pyright/issues/9984
Once ^^ is resolved. We should revert this PR.
=> chore: Temporarily do not use latest pyright version
