- shiny/ui/_input_select.py
> input_selectize() now resolves the input id before using for other id-like attributes

- shiny/_app.py
- shiny/session/_session.py
Fixes #279.
Reactive flush is what causes outputs and errors to get queued up
for sessions; a second step (unforunately also called "flush") is
necessary for those outputs and errors to be sent to clients. This
was achieved by subscribing to reactive._core.on_flushed with a
handler that triggers session._flush.
Shiny's reactive environment is global to a Python process. It is
possible for a single process to run multiple Shiny apps over time.
So the subscription to reactive._core.on_flushed was happening
during app startup and unsubscribed during app shutdown, as reported
via the Starlette lifespan feature.
However, if a Shiny app is mounted to a Starlette route, then its
lifespan never comes into play. This resulted in issue "#279:
reactivity failing when mounting app as route on …
> Remove dependence on Starlette's lifespan mechanism

- shiny/reactive/_reactives.py
With pyright 1.1.266, we started seeing new errors like this:
```
/home/runner/work/py-shiny/py-shiny/shiny/reactive/_reactives.py:411:20 - error: Expression of type "CalcAsync_[Awaitable[T@Calc] | T@Calc]" cannot be assigned to return type "Calc_[T@Calc]"
TypeVar "T@Calc_" is invariant
Type "Awaitable[T@Calc] | T@Calc" cannot be assigned to type "T@Calc" (reportGeneralTypeIssues)
```
This is due to a bug (I think) in pyright: https://github.com/microsoft/pyright/issues/3813
This PR changes the order of types in the `Union` to avoid the false positive.
> Change order of types

- shiny/_main.py
- shiny/_static.py
This PR makes it so that when `shiny static` is called, it runs code provided by the shinylive bundle. This makes it so that shinylive can make changes to how it does deployment, without having to synchronize it with the shiny package.
Along with https://github.com/rstudio/py-shinylive/pull/14, it also makes the following possible:
*****
Multiple applications can be deployed in one command, with:
```py
shiny static app1 site --subdir a1
shiny static app2 site --subdir a2
shiny static app3 site --subdir a3
```
This will create the following directory structure:
```
site
├── a1
│   ├── app.json
│   ├── edit
│   │   └── index.html
│   └── index.html
├── a2
│   ├── app.json
│   ├── edit
│   │   └── index.html
│   └── index.html
├── a3
│   ├── app.json
│   ├── edit
│   │   └── index.html
│   …
```
> Delegate shinylive deployment to code in shinylive

- examples/global_pyplot/app.py
- shiny/render/_render.py
- shiny/render/_try_render_plot.py
Fixes #312.
Turns out it is pretty easy to get at the pyplot global figure. However, this is a bad idea if you are using async, or multiple threads (we don't currently allow this but we might later on).
I added an example at `examples/global_pyplot/app.py`, will write tests against it when we have that infrastructure ready.
> Plot using pyplot global figure

- CHANGELOG.md
- shiny/__init__.py
- shiny/_main.py
- shiny/_static.py
The shinylive package is now on PyPI:
* https://pypi.org/project/shinylive/
* https://github.com/rstudio/py-shinylive
This PR disables `shiny static` and tells the user to install shinylive and use `shinylive export`.
When you run `shiny static`, this is what it now shows:
```
$ shiny static myapp site
The functionality from `shiny static` has been moved to the shinylive package.
Please install shinylive and use `shinylive export` instead of `shiny static`:
shiny static-assets remove
pip install shinylive
shinylive export APPDIR DESTDIR
```
> Deprecate 'shiny static' in favor of 'shinylive export'

- shiny/_autoreload.py
- shiny/_launchbrowser.py
- shiny/_main.py
- shiny/_utils.py
- tests/test_utils.py
With this PR, you can add `--launch-browser` to the `shiny run` command and it will pop open a web browser on successful launch.
It's also possible to ask Shiny to use a random port by passing `--port 0`. This will be helpful for RStudio Server and other multiuser scenarios.
* Tested that `shiny run --reload --launch-browser ...` only launches a browser once, not on each autoreload (i.e. saving `app.py` should cause existing browser window to autoreload but NOT for a new browser window to be launched)
* Tested that `shiny run --launch-browser ...` (i.e. without `--reload`) works; this uses a totally different codepath than `--reload`
* Tested that `--port 0` assigns random port numbers every time
* Tested that `--port 0 --reload` keeps the same random port number for each autoreload
* …
> Add --launch-browser option to shiny run, and random port

- CHANGELOG.md
- e2e/module-conditional/app.py
- e2e/module-conditional/test_module_conditional.py
- shiny/_namespaces.py
- shiny/module.py
- shiny/ui/_bootstrap.py
Fixes #333 
At the HTML markup level, Shiny's conditional panels take a `data-ns-prefix="{moduleid}-"` attribute that tells Shiny to interpret `input.*` and `output.*` expressions as if they are in the context of the given module ID. The Python code was not populating this attribute correctly, because the conditional panel code was written before the module system existed for Python.
No tests needed, I think--I've included an e2e test that should cover it.
> Fix panel_conditional behavior in the context of modules

- shiny/_static.py
- tests/test_static.py
Contents of this MR:
- Fixed `_installed_shinylive_versions` which seemed to be broken, since `shinylive_dir.iterdir()` will return the directories including the root, e.g. `shinylive/shinylive-1` and thus the regex `re.sub("^shinylive-", "", str(s))` did not work. 
- Added unit tests to increase code coverage for this file from `32%` to `82%`.
- Fixed typing; the function `remove_shinylive_local` is only ever called with a `Path` as argument, so changed `Union[str, Path, None]` to `Optional[Path]`.
> Fixed `_installed_shinylive_versions` and added unit tests

- .github/workflows/pytest.yaml
- .pre-commit-config.yaml
- Makefile
- requirements-dev.txt
- setup.cfg
This MR is a smaller version of my initial MR: https://github.com/rstudio/py-shiny/pull/342
The purpose of the MR is to improve developer experience by not having to run multiple commands locally to verify code formatting. Right now, `make check`, `make lint` and `isort .` need to be run separately, and `black` is called by `pre-commit`. This MR proposes to have `make check` verify all aspects of code quality. Next to that, it proposes to introduce `isort` to improve code quality.
- Add [isort](https://github.com/PyCQA/isort) to sort imports.
- Fix `black` URL in `pre-commit-config.yaml`.
- Fixed issue where `flake8` was configured to include specific directories in the `make lint `command, making the `extend-exclude`  in `setup.cfg` obsolete, but also resulting in `make lint` and `flake8 …
> Added isort and repurposed `make check` command

- CHANGELOG.md
- shiny/_main.py
See https://github.com/encode/uvicorn/pull/1640
Fixes `TypeError: run() got an unexpected keyword argument 'debug'`
> Remove --reload flag; this option is no longer in uvicorn

- shiny/_autoreload.py
When using --reload, the HTTP response for the homepage was using Transfer-Encoding: chunked, which is more complicated for proxies than it needs to be. This was happening because we had a script autoinjection middleware that was modifying the body and then just stripping the Content-Length header instead of making it the correct value.
> Stop using chunked encoding

- CHANGELOG.md
- docs/source/index.rst
- docs/sphinxext/pyshinyapp.py
- shiny/_docstring.py
- shiny/examples/file_reader/requirements.txt
- shiny/examples/output_table/requirements.txt
- shiny/ui/_output.py
Closes #240 
Closes #330
Also adds `output_table` and `render.table` to the API reference
> Fix API doc examples that depend on local files

- CHANGELOG.md
- shiny/_main.py
Previously, using `shiny run` with a Windows path with a drive letter would result in an error. For example:
```
C:\Users\Jon\Documents\PyShinyTest>shiny run C:/Users/Jon/Documents/PyShinyTest/app.py
INFO Will watch for changes in these directories: ['C:\Users\Jon\Documents\PyShinyTest']
INFO Uvicorn running on http://127.0.0.1:9092 (Press CTRL+C to quit)
INFO Started reloader process 19484 using StatReload
ERROR: Error loading ASGI app. Could not import module "C".
INFO Stopping reloader process 19484
```
This PR fixes the issue.
> Fix `shiny run` for Windows absolute paths with drive letter

- CHANGELOG.md
- shiny/ui/_input_select.py
- shiny/ui/_input_slider.py
The width was being applied to the control itself, when it really needed to be applied to the input container.
Fixes #385.
> Fix width parameters for input_select and input_slider

- CHANGELOG.md
- shiny/session/_session.py
- tests/test_shinysession.py
This adds a method for `Inputs.__contains__`, so that the user can write code like this:
```py
@Effect
def foo():
if "x" in input:
...
```
When `in` is used, Shiny creates a reactive dependency. If `input.x` starts out nonexistent and then later gains a value, then `foo` will be invalidated and re-executed. After that point, `input.x()` _changes_ value, then this will _not_ cause `foo` to invalidate -- the invalidation only occurs when 
When `x` is not yet set from the client, the interface here makes it look like `x` is not in the `Input` object (when `input.x()` and `"x" in input` are called). The underlying implementation actually does add `x` to the `Inputs`'s internal `_map` object, but that is hidden from the user.
Test application:
```py
from shiny import App, Inputs, Outputs, …
```
> Add `Inputs.__contains__` method

- shiny/examples/update_selectize/app.py
Without this fix, the example throws an error instead of starting.
> Use correct argument to input_selectize

- .github/workflows/pytest.yaml
- Makefile
- setup.cfg
- shiny/examples/Module/app.py
- shiny/render/_render.py
- shiny/session/_session.py
- shiny/types.py
- shiny/ui/__init__.py
- shiny/ui/_bootstrap.py
- shiny/ui/_download_button.py
- shiny/ui/_input_action_button.py
- shiny/ui/_input_check_radio.py
- shiny/ui/_input_date.py
- shiny/ui/_input_file.py
- shiny/ui/_input_numeric.py
- shiny/ui/_input_password.py
- shiny/ui/_input_select.py
- shiny/ui/_input_slider.py
- shiny/ui/_input_text.py
- shiny/ui/_input_update.py
- shiny/ui/_insert.py
- shiny/ui/_modal.py
- shiny/ui/_navs.py
- shiny/ui/_notification.py
- shiny/ui/_output.py
- shiny/ui/_page.py
- shiny/ui/_utils.py
This PR updates Shiny to use types from htmltools 0.1.4.9001.
> Use types from htmltools 0.1.4.9001

- .github/requirements-tox.txt
- .github/workflows/pytest.yaml
- Makefile
- e2e/README.md
- setup.cfg
Fixes #417 
--------------------------------------------
`tox` was introduced to the repo in #320
A clear article on why `tox` is useful: https://christophergs.com/python/2020/04/12/python-tox-why-use-it-and-tutorial/
tl/dr 
> * Test against different versions of Python (which would have alerted Kyle that the library hadn’t been tested against his install version).
> * Test against different dependency versions
> * Capture and run setup steps/ad hoc commands (which Kyle could have made a mistake on / not known about)
> * Isolate environment variables - By design, tox does not pass any evars from the system. Instead you are asked to explicitly declare them (which would have alerted Kyle to any environment variable requirements).
> * Do all the above across Windows / macOS / Linux (which …
> Remove `tox` from e2e testing

- .github/workflows/pytest.yaml
> Add test support for mac and windows

- CHANGELOG.md
- shiny/__init__.py
- shiny/_app.py
Related: `Add URL support to HTMLDependency` - https://github.com/rstudio/py-htmltools/pull/53
> Allow for htmldeps with no source file location

- setup.cfg
- shiny/ui/_input_check_radio.py
After https://github.com/rstudio/py-htmltools/pull/54 is merged, a few components need explicit whitespace.
> Update functions to use new htmltools whitespace behavior

- CHANGELOG.md
- shiny/session/_session.py
Closes #443.
For streaming downloads, adding the header `Transfer-Encoding: chunked` lets the client know that it should keep receiving data until it gets a terminating chunk (with size zero). If the transfer ends before then, then the client knows there was an error.
https://stackoverflow.com/a/40282512/412655
Now with the download test app, an error in a streaming download results in this showing in Chrome:
> For streaming downloads, add `Transfer-Encoding: chunked` header

- setup.cfg
- shiny/_app.py
- shiny/_utils.py
- tests/test_utils.py
Other changes
* Make random port test more robust. 
* GitHub Desktop uses port `9010`
* Set the timeout to 2s
* If a port is busy, shift the testing port range
* Use `random.randint(min, max)` for uniform port
* Rounding _technically_ isn't uniform. Using a single method is less complicated.
> Make random port test more robust

- CHANGELOG.md
- shiny/ui/_navs.py
- shiny/ui/_page.py
Previously, this would raise an error, because `page_navbar` expected _only_ `NavSetArg` objects, but `shinyswatch.theme.darkly()` is a list of HTML Dependencies.
```py
ui.page_navbar(
shinyswatch.theme.darkly(),
ui.nav( ... ),
)
```
This PR allows it to accept `MetadataNode` objects and lists/tuples of them.
> Allow `page_navbar` to accept HTML dependencies

- CHANGELOG.md
- shiny/plotutils.py
> Use explicit `int64` when converting `datetime`s

- shiny/_app.py
- tests/test_ui_dependencies.py
Even if the htmldependency version is higher or lower, the HTML being sent to the user is requesting THIS dependency. Therefore, it should be available to the user independent of any previous versions of the dependency being served.
`{htmltools}` does de-duplicate dependencies and finds the highest version to return. However, dynamic UI and callable UI do not run through the same filter over time. When using callable UI functions, UI dependencies are reset
on refresh. So if a dependency makes it here, it is not necessarily the highest version served over time but is the highest version for this particular UI. Therefore, serve it must be served.
> Independent of dependency version, serve it if requested

- shiny/_utils.py
The use of `ParamSpec` makes it possible for these functions to work on functions that have arguments, and to pass those arguments types along to the returned function.
> `wrap_async()` and `is_async_callable()` now allow functions with args

- CHANGELOG.md
- shiny/__init__.py
- shiny/experimental/ui/__init__.py
- shiny/experimental/ui/_input_text.py
- shiny/experimental/www/textarea-autoresize.css
- shiny/experimental/www/textarea-autoresize.js
This PR adds Added `shiny.experimental.ui.input_text_area()`, which has a new `autoresize` option. When `autoresize=True`, the height will automatically resize to fit the content.
> In `experimental`, add `ui.input_text_area` with `autoresize` option

- shiny/_main.py
Introduced in #505
[Current error](https://github.com/rstudio/py-shiny/actions/runs/5050502625/jobs/9061290514?pr=505) that I can't reproduce locally:
```
INTERNALERROR> E             SystemError: AST constructor recursion depth mismatch (before=141, after=191)
INTERNALERROR> E           assert False
```
> Fix e2e-examples

- shiny/ui/_html_dependencies.py
> fix: add meta viewport tag

- shiny/experimental/e2e/accordion/app.py
- shiny/experimental/examples/accordion_panel_update/app.py
- shiny/experimental/ui/__init__.py
- shiny/experimental/ui/_accordion.py
Matches ui function names using `update_*()` style
> fix(x.ui.accordion): Rename `accordion_panel_update()` to `update_accordion_panel()`

- shiny/examples/download_button/app.py
- shiny/examples/download_link/app.py
I thought about updating the links but realised that the `py-shiny/shiny/examples/download/app.py` shows a full set of examples, and with `py-shiny/shiny/examples/download_button/app.py` and `py-shiny/shiny/examples/download_link/app.py` covering link and button specific examples, the comment was no longer necessary.
This addresses issue https://github.com/rstudio/py-shiny/issues/555
> chore: remove dead links from comments

- examples/penguins/app.py
- setup.cfg
Note that the value boxes still are laid out vertically instead of horizontally. That still needs to be fixed.
> Use wrapping form of `as_fill_item()` in penguins app

- .github/workflows/pytest.yaml
- MANIFEST.in
- Makefile
Without this, the data frame feature only works when you `pip install -e`, not a regular pip install, because the JS assets are not included in the source package.
Also update Makefile/CI so we catch this with automated tests in the future.
> Update manifest to bundle built JS for tanstack table

- setup.cfg
Closes #593 
`contextvars` has been in the standard library since python 3.7. We should remove it from setup.cfg so that pip doesn't try to install the [backport](https://pypi.org/project/contextvars/).
> fix: drop contextvars from setup.cfg

- setup.cfg
- shiny/_main.py
- shiny/_typing_extensions.py
@jcheng5 My questionable change is adding the name to `click.group()`. Is this an ok change?
-----------------------
```
pyright
/home/runner/work/py-shiny/py-shiny/shiny/_main.py
/home/runner/work/py-shiny/py-shiny/shiny/_main.py:24:2 - error: Untyped function decorator obscures type of function; ignoring decorator (reportUntypedFunctionDecorator)
/home/runner/work/py-shiny/py-shiny/shiny/_main.py:32:7 - error: Cannot access member "command" for type "function"
Member "command" is unknown (reportFunctionMemberAccess)
/home/runner/work/py-shiny/py-shiny/shiny/_main.py:370:7 - error: Cannot access member "command" for type "function"
Member "command" is unknown (reportFunctionMemberAccess)
/home/runner/work/py-shiny/py-shiny/shiny/_main.py:399:7 - error: Cannot access member "command" for …
```
> bug(typing): Fix typing issues in latest `click` package

- shiny/_main.py
I like running with `shiny run --reload --launch-browser` but it's taken me a long time to remember the spelling of those options. But `shiny run -rb` is much easier for me to remember and type.
I didn't add aliases for everything, only the more obvious ones.
> feat(cli): add short aliases to shiny run args

- Makefile
- shiny/render/_coordmap.py
- shiny/render/_try_render_plot.py
> Use enhanced matplotlib type stubs

- examples/penguins/app.py
It seems like there's a matplotlib regression which causes our CI to fail [Issue #611](https://github.com/rstudio/py-shiny/issues/611). Since I was trying to debug this issue on another branch I went ahead and silenced that warning on the penguins app.
> Silence figure layout warning on matplotlib 3.7.2

- shiny/_app.py
- shiny/_main.py
- shiny/input_handler.py
- shiny/ui/_include_helpers.py
Code blocks with `.. code-block:: python` currently render like this with Quarto and Quartodoc:
This PR converts them to Quarto-style code blocks as described here: https://machow.github.io/quartodoc/get-started/docstring-examples.html#examples-using-code-blocks
> Fix example code blocks

- shiny/_main.py
Without this, `shiny run --app-dir=foo app.py` won't work even if foo/app.py exists and is a valid Shiny app. This is because the code that turns `app.py` into `app:app` for Uvicorn wasn't aware of --app-dir.
> Make --app-path work with app file argument

- CHANGELOG.md
- e2e/bugs/0648-update-slider-datetime-value/app.py
- e2e/bugs/0648-update-slider-datetime-value/test_update_slider_datetime_value.py
- shiny/ui/_input_update.py
> Allow ui.update_slider to handle non-numeric values

- .github/workflows/triage-issues.yaml
The goal of this PR is to do the following:
- All issues from team members get immediately added to the project board
- All issues from the community get labelled with a "needs-triage" label so that we can respond to them more promptly
On the project board I've set up a job which pulls in all tickets without a "needs-triage" label.
> Add a triage label to issues created by non-maintainers

- CHANGELOG.md
- e2e/bugs/0666-sidebar/app.py
- e2e/bugs/0666-sidebar/colors.py
- e2e/bugs/0666-sidebar/test_sidebar_colors.py
- shiny/ui/_x/_htmldeps.py
Fixes #666
Missing related code change in main code: [f525802](https://github.com/rstudio/py-shiny/commit/f525802#diff-eaa202345de79d2b4af2eeedff977b7cb9317cf415a2b901b6f85214505ddc95R56)
> Add missing sidebar stylesheet dep

- e2e/data_frame/test_data_frame.py
I've ran into 5+ situations where this test has failed in other (unrelated) PRs. 
The root cause is the diamonds table take an extra second to load. This may time out on CI, but will pass locally. By changing the test and increasing the timeout, it should be clearer if the test fails and should occur less often (hopefully never due to timing).
cc @jcheng5
> Make flaky dataframe test have larger timeout

- examples/model-score/scoredata.py
The `scoredata.begin()` function gets called from the top-level of app.py, that is, at module load time. When I was testing this locally and in shinylive, it was fine to use `asyncio.create_task()` here, because an asyncio event loop was already started courtesy of uvicorn by the time the app module is imported. But in Connect, the app module is imported way earlier, because Connect has ASGI middleware it needs to install around it. In that case, no asyncio event loop exists and we have to do something else.
I guess another way to do this would've been to use a one-shot reactive Effect at the top level. Seems like a weird pattern to promote.
Another would be to introduce start/stop callbacks on the App object. Or `app.starlette_app.add_event_handler("startup", scoredata.begin)` works …
> Make model score app work on Connect/Shinyapps.io

- CHANGELOG.md
- shiny/session/_session.py
- tests/e2e/session/flush/app.py
- tests/e2e/session/flush/test_on_flush.py
Execute the functions asynchronously, one after another
Fixes #686
> feat(Session): Make Session on_flush() and on_flushed() accept async functions

- Makefile
- examples/static_plots/app.py
- setup.cfg
- shiny/render/_try_render_plot.py
- tests/e2e/examples/test_examples.py
> Remove warnings from external packages when testing shiny examples

- scripts/htmlDependencies.R
- shiny/www/shared/ionrangeslider/css/ion.rangeSlider.css
Fixes #748
The prebuilt `ionRangeSlider.css` now includes the additional rules we added in the shiny preset in bslib. This ensures that the slider styles are consistent, even when the slider is used in a context where py-shiny's core bootstrap bundle isn't available (e.g. Quarto).
For a minimal diff and to match the current py-shiny dependencies, I used the following instead of installing each package from `@main`:
```r
pak::pkg_install(c(
"rstudio/bslib@a076e72e78562d7f006889da4118cd781c66c84c",
"rstudio/shiny@68546c319e465a9cb113ea4499912823e264e75f",
"rstudio/htmltools@9338b7f3e2ed7b3fef8fd813904b9b05281344aa"
))
```
> fix(ionrangeslider): Bring in the shiny-preset ionrangslider rules to the precompiled CSS

- Makefile
- shiny/render/_try_render_plot.py
- tests/e2e/plot-sizing/app.py
- tests/e2e/plot-sizing/test_plot_sizing.py
This fixes a bug introduced by #783, which was intended (in part) to allow render.plot code to set plot sizes by using matplotlib figure sizing. That code assumed that only explicit user code would cause the figure size to differ from matplotlib's default figure size (plt.rcParams["figure.figsize"]). But that's not true for seaborn, which likes to set its own sizes, which we then misidentified as being a high priority size directive that we should obey.
https://seaborn.pydata.org/tutorial/function_overview.html#specifying-figure-sizes
This change removes the logic that looks at whether the figure size changed. Instead, render.plot width/height can be set to 0 to cause the matplotlib figure size to be honored. However, we're not going to be emphasizing that in our docs, at least for now.
> Seaborn plots should fill their output_plot

- shiny/api-examples/template/app.py
So we don't forget to remove the `@output` from the default app before the next release. I also added a `panel_title` instead of an `h2` so that the app shows up in the browser tab.
> Remove output from template app

- shiny/ui/_sidebar.py
Related: https://github.com/rstudio/bslib/pull/841/files#diff-363b351490c118118d1a95c0ee882a23303d7353746351a8cc63e0f2a1855d59
cc @wch
> bug(sidebar): Revert sidebar icon back to chevron

- shiny/session/_session.py
The `Outputs` class constructor has a deprecated parameter `name`. It was deprecated over a year ago in #220 and can be safely removed now.
> Remove deprecated 'name' parameter from `Outputs`

- shiny/render/_render.py
- shiny/render/transformer/_transformer.py
- tests/e2e/plot-sizing/test_plot_sizing.py
- tests/pytest/test_plot_sizing.py
Previously, default width/height value from render.plot (None) was passed to implicit plot output. With this fix, use MISSING as the default parameter value to make it clear that the default value is not set and shouldn't be passed through.
> Fix default width/height with implicit plot output

- shiny/_main.py
- shiny/express/_run.py
- shiny/express/_utils.py
- shiny/express/app.py
- tests/pytest/test_express_utils.py
For running Express apps, this PR makes it so that setting an environment variable is no longer needed for uvicorn to launch the app; instead, if the app path is:
```
path/to/app.py
```
then this sets the entrypoint to
```
shiny.express.app:path_2f_to_2f_app_2e_py
```
This will make it possible to deploy on shinyapps.io.
The escaping rule is this:
- For all characters that are _not_ numbers or letters escape them by replacing with `_<hex>_`, where `<hex>` is the hexadecimal representation of the character.
- In addition, if the first character is a number, escape it the same way. This is because variable names in Python can't start with a number. For example, `0app_2e_py` is not a valid name, and so can't be used as part of an entrypoint, as in  `shiny.express.app:0app_2e_py`.
In my …
> Use path to app as part of entrypoint for Express apps

- .github/workflows/build-docs.yaml
- README.md
This PR makes it so deploys the docs built from `main` are deployed on GitHub Pages.
> Deploy dev docs on GitHub Pages

- tests/e2e/ui/accordion/test_accordion.py
I don't know why the test is hanging. The methods have been called before and work as expected. For now, disabling the last part of the test
> test(e2e): Disable accordion test that is causing pytest to hang on failure

- CHANGELOG.md
- docs/_quartodoc.yml
- shiny/reactive/__init__.py
- shiny/reactive/_poll.py
- shiny/reactive/_reactives.py
- shiny/session/_session.py
- tests/deploys/apps/plotly_app/app.py
- tests/e2e/TODO/sidebar/app.py
- tests/e2e/TODO/update_popover/app.py
- tests/e2e/async/app.py
- tests/e2e/bugs/0648-update-slider-datetime-value/app.py
- tests/e2e/bugs/0696-resolve-id/app.py
- tests/e2e/inputs/input_file/app.py
- tests/e2e/navs/navset_hidden/app.py
- tests/e2e/session/flush/app.py
- tests/e2e/ui/accordion/app.py
- tests/e2e/ui/popover/app.py
- tests/e2e/ui/tooltip/app.py
- tests/pytest/test_modules.py
- tests/pytest/test_poll.py
- tests/pytest/test_reactives.py
- tests/pytest/test_shinysession.py
This closes #814.
Many users have wondered why `reactive.Value`, `.Calc`, and `.Effect` are capitalized. There are technical reasons for this, but from a user perspective it makes more sense to just use lowercase names.
This PR changes those names to lowercase, and adds aliases so that the old capitalized names still work. 
This PR does not change any examples because if users on a previous version of shiny were to use the example code, it wouldn't work for them, and it would be unclear to them why. In a future release, we should update the examples to use the new lowercase names.
> Add lowercase `reactive.value`, `calc`, `effect`

- shiny/express/display_decorator/_display_body.py
- shiny/quarto.py
Also small fix to make Shiny Express compile cleanly even if there are no code cells. I ran into this when I made a minimal server:shiny .qmd and tried to run it.
> Make @display_body and @render.display work in Jupyter cells

- shiny/ui/_page.py
> Make sure the fill HTML dependency comes for the ride with `page_fillable()`

- shiny/express/_run.py
Closes #846.
With this PR, `page_fillable()` becomes the new page default for express. This should lead to the same experience as before for non-fill items (e.g., inputs, text, etc), but fill items like plots, cards, layouts, etc. will now fill the page (when wide enough).
Moreover, this default is more consistent with the `with layout.sidebar()` experience, which treats the main content area as a fillable container (by default).
For a concrete example, notice that the plot here will now fill the page:
```python
from shiny import App, render, ui
from shiny.express import input
ui.input_slider("slider", label="Slider", min=0, max=100, value=50)
@render.plot()
def plt():
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x * input.slider())
fig, …
```
> Make `page_fillable()` the default for express mode

- CHANGELOG.md
- shiny/api-examples/as_fill_item/app.py
- shiny/api-examples/as_fillable_container/app.py
- shiny/experimental/ui/_deprecated.py
- shiny/ui/_navs.py
- shiny/ui/_page.py
- shiny/ui/_tag.py
- shiny/ui/fill/_fill.py
- tests/pytest/test_navs.py
This is a follow-up to https://github.com/posit-dev/py-shiny/pull/861#discussion_r1418189057. Also closes #577.
This PR makes it so that `as_fillable_container()` and `as_fill_item()` do not modify their inputs.
Fixes #865
> Make `as_fillable_container()` and `as_fill_item()` not mutate their inputs

- shiny/express/_run.py
Because the Express API is still evolving, we want to make it clear to users that the API could change in a way that breaks their app. The idea is that this warning would be in the next release of Shiny, but _not_ in the release after that.
The warning looks something like this:
```
WARNING:root:Detected Shiny Express app. please note that Shiny Express is still in development and the API is subject to change!
INFO:     Started server process [8187]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:52623 (Press CTRL+C to quit)
```
I looked into making it so that it only warns once when you call `shiny run --reload`, but that ended up being pretty complicated to implement, because every time the app reloads, it …
> Print a warning message when running Express app

- Makefile
- tests/playwright/shiny/shiny-express/page_default/app.py
- tests/playwright/shiny/shiny-express/page_default/test_page_default.py
1. Fix the `pyright` errors since recent code changes in Shiny express from `navset_tab()` ->` navset()` and `navset_card_tab()` -> `navset_card()`
2. install main version of `rsconnect-python` instead of pypi since pypi version does not yet support shiny express tests and we want to test shiny express tests.
3. Modify name of the test since it was copied from another test and not changed to reflect the test file name.
> Fix failing express tests

- shiny/express/_run.py
This closes #869.
Previously in the case of an `AttributeError`, it would print this:
```
ERROR:    Error loading ASGI app. Attribute "_2f_Users_2f_winston_2f_Projects_2f_py_2d_shiny_2f_examples_2f_express_2f_plot_5f_app_2e_py" not found in module "shiny.express.app".
```
With this PR, it will print a normal stack trace and then a `RuntimeError`:
```
...
File "/Users/winston/Library/py-shiny/shiny/express/app.py", line 13, in __getattr__
return wrap_express_app(Path(name))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/winston/Library/py-shiny/shiny/express/_run.py", line 44, in wrap_express_app
app_ui = run_express(file)
^^^^^^^^^^^^^^^^^
File "/Users/winston/Library/py-shiny/shiny/express/_run.py", line 129, in run_express
raise RuntimeError(e)
RuntimeError: This is an error
```
This PR …
> Better messages for `AttributeError` in Shiny Express

- .gitignore
- pyrightconfig.json
- setup.cfg
Excludes `_dev/` from project-level tracking, linting and type checking.
This is the folder I typically use to track notes, reprex and examples apps, design documents, etc. The underscore helps `_dev/` float to the top of the file tree and separates it from general project folders.
> chore: exclude `_dev/` folder 

- shiny/ui/_layout_columns.py
Mostly relevant in the case of `col_widths` being a single value or a tuple/list.
> fix(layout_columns): If the breakpoint name is an enum, need to collect the value

- shiny/ui/_layout_columns.py
Adds the `.bslib-mb-spacing` class to the `bslib-layout-columns` component to ensure that it receives bottom margin outside of gap-driven spacing contexts.
<details>
<summary>Example App</summary>
```python
from shiny import App, render, ui
app_ui = ui.page_navbar(
ui.nav(
"Page 1",
ui.layout_columns(
ui.fill.as_fill_item(ui.div({"class": "bg-primary ex-box"})),
ui.fill.as_fill_item(ui.div({"class": "bg-secondary ex-box"})),
),
ui.layout_columns(
ui.fill.as_fill_item(ui.div({"class": "bg-warning ex-box"})),
ui.fill.as_fill_item(ui.div({"class": "bg-danger ex-box"})),
),
ui.tags.style(".ex-box { min-height: 100px !important; }"),
),
fillable=False,
)
def server(input, output, session):
...
app = App(app_ui, server)
```
</details>
> fix(layout_columns): Add missing `bslib-mb-spacing` class

- shiny/ui/_layout_columns.py
I was accidentally applying the fillable class to both the children and the parent layout columns container; instead `fillable` should be applied to wrapper where the children are placed and `fill` is applied to the layou container.
> fix(layout_columns): Don't apply fillable class to layout container

- shiny/api-examples/layout_column_wrap/app.py
- shiny/ui/_layout.py
- shiny/ui/_layout_columns.py
Fixes #899
This PR moves and renames `ui._layout_columns.wrap_all_in_grid_item_container()` to `ui._layout.wrap_all_in_gap_spaced_container()`. This helper function adds the `bslib-gap-spacing` class, plus any item-specific classes, and optionally turns on fillability for that container.
I also fixed a typo in the example for `layout_column_wrap()`.
> refactor(layout_column_wrap): Use helper for wrapping children

- setup.cfg
- shiny/express/_recall_context.py
- shiny/render/_display.py
- tests/playwright/utils/express_utils.py
Closes #872.
This PR makes it so strings (and other types of objects) are not automatically wrapped in a `<pre>` block, as described in https://github.com/posit-dev/py-shiny/issues/872#issuecomment-1852630725.
> Express: don't automatically put strings in a `<pre>` block

- tests/playwright/deploys/apps/plotly_app/requirements.txt
- tests/playwright/deploys/apps/shiny-express-accordion/requirements.txt
- tests/playwright/deploys/apps/shiny-express-page-default/app.py
- tests/playwright/deploys/apps/shiny-express-page-default/requirements.txt
- tests/playwright/deploys/apps/shiny-express-page-fillable/requirements.txt
- tests/playwright/deploys/apps/shiny-express-page-fluid/requirements.txt
- tests/playwright/deploys/apps/shiny-express-page-sidebar/requirements.txt
The deploy tests were using an older version of `py-htmltools` because it was missing `.git` in requirements.txt
Also, use `navset_card` instead of `navset_card_tab` for shiny express
> Fix failing deploy tests

- MANIFEST.in
Closes #922
Note that #922 is only reproducible if you do a non-editable install (e.g.,  `pip install .`)
> Add shiny/templates to MANIFEST.in files

- shiny/_app.py
- shiny/_namespaces.py
- shiny/_utils.py
- shiny/express/_is_express.py
- shiny/express/_output.py
- shiny/express/_run.py
- shiny/express/app.py
- shiny/express/display_decorator/_display_body.py
- shiny/express/layout.py
- shiny/http_staticfiles.py
- shiny/input_handler.py
- shiny/reactive/_core.py
- shiny/render/_try_render_plot.py
- shiny/render/transformer/_transformer.py
- shiny/session/_session.py
When shiny type stubs are generated by pyright, and they are used for types (instead of using the shiny source code directly), we have some typing errors, which are visible in shinylive:
This is because some of the .pyi files generated by pyright lack necessary type information. This PR fixes most cases of missing types in the .pyi files, but not all.
@schloerke in the future we should have an automated test which runs pyright on the generated .pyi files, as well as the examples (but using the shiny type stubs instead of shiny sources directly).
******
To illustrate what's going on, here's the relevant part of [`OutputTransformer`](https://github.com/posit-dev/py-shiny/blob/d541388a2c82750bcbae4c2f8731447cb37ee71a/shiny/render/transformer/_transformer.py#L541-L604) from _transformer.py …
> Add fixes for type stub generation

- CHANGELOG.md
- shiny/_template_utils.py
This fixes #935.
I tested with this, which still works:
```
shiny create -g https://github.com/posit-dev/py-shiny-templates/tree/main/dashboard
```
And if you give it a nonexistent URL, like this:
```
shiny create -g https://github.com/posit-dev/nothinghere/tree/main/dashboard
```
The previous error message looked like this:
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/posit-dev/nothinghere/archive/refs/heads/main.zip
```
After this PR, it looks like this:
```
urllib.error.HTTPError: HTTP Error 404: Not Found for url: https://github.com/posit-dev/nothinghere/archive/refs/heads/main.zip
```
> Switch from `requests` to `urllib`

- shiny/express/_run.py
> Call `tagify()` early to intercept `AttributeErrors`

- shiny/express/ui/__init__.py
- shiny/express/ui/_cm_components.py
> Include `tooltip()` and `popover()` in express

- shiny/express/ui/_cm_components.py
Currently a `shiny.express.ui.value_box()` _must_ be created with positional arguments passed to the context manager.
```python
with ui.value_box("title", "value"):
pass
```
With this PR, those `title` and `value` positional args will go away in favor of taking the 1st 2 children as the title and value:
```python
with ui.value_box():
"title"
"value"
```
Not only does this feel more "express-like" to me, but it'll be much easier to render reactive values.
> Express' `value_box()` no longer includes named positional args

- CHANGELOG.md
- README.md
- shiny/_custom_component_template_questions.py
- shiny/_main.py
- shiny/_template_utils.py
- shiny/templates/package-templates/js-react/srcts/index.tsx
- tests/pytest/test_shiny_create.py
This closes a bunch of issues from the QA bug bash. 
Fixes #961
Fixes #960 
Fixes #958 
Fixes #957 
Fixes #956 
Fixes #962
> Shiny create bugs

- CHANGELOG.md
Adds a note about the changes in #920 under "Other changes"
> docs: Add changelog item for #920

- shiny/__init__.py
- shiny/api-examples/Renderer/app.py
- shiny/render/_display.py
- shiny/render/_render.py
- shiny/render/renderer/_renderer.py
- shiny/render/transformer/_transformer.py
- shiny/templates/package-templates/js-output/custom_component/custom_component.py
- shiny/templates/package-templates/js-react/custom_component/custom_component.py
I like the new name more after looking at it a bunch.
Also, make sure all `Renderer` value functions are received as `_fn`.
> Change `Renderer.value_fn` to `Renderer.fn`

- shiny/api-examples/input_action_button/app-express.py
For #987
Adds a Shiny Express version of `shiny/api-examples/input_action_button/app.py`.
> [!NOTE]
> I did this PR in two steps so you can see the change in syntax from `app.py` → `app-express.py`. You don't need to commit these as separate steps.
>
> Mention the parent issue and add @gadenbuie as a reviewer (I can't add myself on this PR).
> [!TIP]
> Run `black` and `isort` on the `app-express.py` file before committing, otherwise CI checks may fail.
>
> ```
> cd shiny/api-examples/input_action_button/
> black app-express.py
> isort app-express.py
> ```
> Express translation of `shiny/api-examples/input_action_button`

- CHANGELOG.md
- shiny/__init__.py
- shiny/api-examples/Renderer/app.py
- shiny/render/_display.py
- shiny/render/renderer/__init__.py
- shiny/render/renderer/_renderer.py
- shiny/render/transformer/__init__.py
- shiny/render/transformer/_transformer.py
- shiny/templates/package-templates/js-output/custom_component/custom_component.py
- shiny/templates/package-templates/js-react/custom_component/custom_component.py
- tests/playwright/examples/test_examples.py
- tests/playwright/shiny/server/output_transformer/app.py
- tests/playwright/shiny/server/output_transformer/test_output_transformer_async.py
- tests/pytest/test_output_transformer.py
- tests/pytest/test_renderer.py
Reverting type change in transformer as to not break existing renderers when we will be switching to Renderer very shortly.
> Revert `render.transformer.ValueFn` type change; Require pkg authors to type `Optional` for `render.renderer.ValueFn`

- CHANGELOG.md
- examples/annotation-export/app.py
- shiny/api-examples/download/app.py
- shiny/api-examples/download_button/app.py
- shiny/api-examples/download_link/app.py
- shiny/render/__init__.py
- shiny/render/_render.py
- shiny/session/_session.py
- shiny/ui/_download_button.py
- tests/playwright/shiny/bugs/0696-resolve-id/app.py
This PR adds `render.download`, and supersedes #967.
The existing API is to use `session.download`, like this:
```py
ui.download_button("dl", "Download File")
@session.download(filename="hello.txt")
def dl():
yield "Hello, world!\n"
```
This is quite a bit different from all other outputs, because it relies on the `session` object. This also doesn't work for Express apps, because there isn't a `session` object available. (I'll note here that it would be possible to add a `session` object that could be imported from `shiny.express`, but the change in this PR is a better one.)
With this PR, the app uses `render.download` instead of `session.download`:
```py
ui.download_button("dl", "Download File")
@render.download(filename="hello.txt")
def dl():
yield "Hello, world!\n"
```
I think this …
> Add `render.download`, take 2

- CHANGELOG.md
- shiny/ui/_page.py
Closes #938. This PR changes `page_sidebar()` and `page_navbar()` to default to `fillable=False`.
> Change `page_sidebar()` and `page_navbar()` to default to `fillable=False`

- shiny/express/_recall_context.py
- tests/pytest/test_express_ui.py
> Cause RecallContextManagers to run when used without `with`

- setup.cfg
There have been issues reported where Shiny apps deployed to Posit Connect break with the latest release of starlette/fastapi. This should keep folks from running into that (for now; we can remove this after a while once Posit Connect customers have time to upgrade with the fix).
> Pin starlette version below 0.35

- shiny/_utils.py
- shiny/render/renderer/_renderer.py
This closes #1010. The latest version of flake8-bugbear added some new checks which were causing test failures.
> Fixes for flake8

- shiny/render/_try_render_plot.py
To calculate accurate coordinate mappings for matplotlib (& plotnine) plots
in display coordinates, the figure should know the location of it's subplots.
The location determined by the subplot parameters (subplot_params) and they
come from one or more of these sources, listed from lowest to highest priority:
1. rcParams
2. plt.subplots(..., gridspec_kw={..., **subplot_params})
3. fig.subplot_adjust(**subplot_params)
4. layout engine
The layout engine has the last say as it dynamically calculates subplot_params
and calls fig.subplot_adjust() to set them.
There are two things to consider:
1. Only layout engines that are "adjust_compatible" calculate subplot_params
2. Matplotlib runs the layout engine only when drawing the figure
This PR ensures that there is an "adjust_compatible" layout …
> Calculate coordinate mapping after drawing figure

- shiny/express/_run.py
Closes #991.
Previously if an app accessed `input.x` at the top level, it would result in this error:
```
RuntimeError: 'builtin_function_or_method' object has no attribute 'x'
```
After this change, this is the error message:
```
RuntimeError: Tried to access `input`, but it was not imported. Perhaps you need `from shiny.express import input`?
```
> Provide useful message in Express when `input` was not imported

- CHANGELOG.md
- shiny/render/__init__.py
- shiny/render/_deprecated.py
- shiny/render/transformer/__init__.py
- shiny/render/transformer/_transformer.py
- tests/playwright/examples/example_apps.py
- tests/playwright/shiny/server/output_transformer/test_output_transformer_async.py
- tests/pytest/test_output_transformer.py
> bug: Restore legacy renderers while packages transition

- shiny/ui/_page.py
If internally-added styles are constructed by hand and not with the help of `css()`, we need to include the semicolon. Otherwise users styles will be space-separated with our internal property declarations, leading to broken `style` attributes.
> fix(page_sidebar): Add semicolon to end style declaration

- shiny/express/ui/_page.py
- shiny/ui/_page.py
> `express.ui.page_opts(title = ...)` now always generates a header

- shiny/render/_display.py
Changes the error thrown by `@render.display` when the decorated function has a return value from
```
@render.display functions should not return values. (`None` is allowed).
```
to
```
@render.display functions should not return values. Instead, the function
body should include Shiny Express code that will be dynamically rendered
in the app. (`None` is a valid return value.)
```
Is `@render.display` intended only for Shiny Express? (If yes, this does speak to having `shiny.express.render` and for not including `render.display` in `shiny`.)
@schloerke described `@render.display` as follows on Slack:
> * `render.ui` renders the last thing returned.
> * `render.display` renders every printable line within the function.
If `render.display` is intended for Shiny Core as well then we could …
> chore(render.display): Improve error message

- docs/_quartodoc.yml
- shiny/__init__.py
- shiny/express/_output.py
- shiny/reactive/_reactives.py
- shiny/render/_deprecated.py
- shiny/render/renderer/__init__.py
- shiny/render/renderer/_renderer.py
- shiny/render/transformer/_transformer.py
- shiny/session/_session.py
- tests/playwright/shiny/components/data_frame/test_data_frame.py
- tests/pytest/test_output_transformer.py
- tests/pytest/test_utils.py
* Removes RendererBase class.
* `RendererBaseT` -> `RendererT`
* Hard deprecate `RenderFunction` / `RenderFunctionAsync`
* The `RenderFunction.__call__(self)` method was an `@abstractmethod`. This method's signature and intent did not agree with `Renderer.__call__(self, _fn: ValueFn[...])`. 
* This might occur with older versions of `shinywidgets` with newer versions of `shiny`.
* This goes against https://github.com/posit-dev/py-shiny/issues/1003 in that now the methods are hard deprecated. But at least the message is much clearer on how to move forward.
> api!: Merge RendererBase class into Renderer

- shiny/render/_try_render_plot.py
PR #999 depended on matplotlib's layout engine API, which was added in matplotlib 3.6.
Matplotlib is currently on 3.8, so normally this would be OK. However, the version of Pyodide we're using in Shinylive comes with matplotlib 3.5.2, so plots don't work at all on that platform -- it simply throws an error when `fig.get_layout_engine()` is called. This PR restores support for older versions of matplotlib.
@has2k1 I'm going to merge this soon to get the dev version of shinylive working again, but please take a look at the PR when you have a chance to make sure it looks good.
> Restore support for matplotlib<3.6

- shiny/express/__init__.py
- shiny/express/_mock_session.py
- shiny/express/_run.py
- shiny/reactive/_reactives.py
Closes #1034.
This PR makes it so that when a `@reactive.effect` is used in the UI-rendering phase of a Shiny Express app, it's a no-op; it doesn't schedule the function to be run later, during a reactive flush.
Some thoughts about how this might be improved/generalized in the future:
- `MockSession` and `Session` could to both be subclasses of another class, like `BaseSession`. Or `MockSession` could just be a subclass of `Session`.
- In `effect.__init__()`, it currently does an explicit check if `session` is a `MockSession` object, but that is a bit crude. Instead, `Session` and `MockSession` could have a method, like `is_reactive()`, which `effect.__init__()` could query to find out whether it should schedule execution on a reactive flush.
- The `MockSession.__init__()` method could …
> Don't run `effect`s created in a `MockSession`

- shiny/express/ui/__init__.py
- shiny/ui/__init__.py
`fill` is currently imported into `shiny.ui`, but are not listed in the `__all__` in that file. This PR:
- Adds it to `__all__` in `shiny.ui`
- Imports it into `shiny.express.ui` and also adds them to `__all__` in that file.
Note that this PR doesn't do the same for `css`. This is because `css` is meant for internal use.
> Add `fill` to `__all__` in `ui` and `express.ui`

- setup.cfg
- shiny/templates/app-templates/dashboard/app-core.py
- shiny/templates/app-templates/dashboard/app-express.py
This adds an express template for the dashboard application. I decided to go with a slightly more repetitive implementation than is strictly necessary, my thought is that adding in `@expressify` here is a bit too much complexity for the user of this dashboard and it's better to have it show a simple implementation even if it's a bit wordy. I'm not attached to this decision if we want to go another route.
> Update dashboard template

- shiny/express/__init__.py
This closes #1065.
Now, if the user does an import outside of an Express app, it will not throw immediately, but it will throw if they try to use the object.
```
>>> from shiny.express import *
>>> input
<shiny.express._ExpressOnlyPlaceholder object at 0x1044c0490>
>>> input.d
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/winston/Projects/py-shiny/shiny/express/__init__.py", line 73, in __getattr__
raise RuntimeError(
RuntimeError: shiny.express.input can only be used inside of a Shiny Express app.
>>> session
<shiny.express._ExpressOnlyPlaceholder object at 0x107897a10>
>>> session.d
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/winston/Projects/py-shiny/shiny/express/__init__.py", line 73, in __getattr__
raise …
```
> Raise when `express.[input,output,session]` are used outside of Express app

- .github/py-shiny/setup/action.yaml
- .github/workflows/build-docs.yaml
- setup.cfg
> chore: Remove github link to shinylive

- CHANGELOG.md
- shiny/api-examples/download_button/app-express.py
- shiny/render/_render.py
This PR supersedes #1084.
Note that the solution here is similar to the one in used #1049. In the future, it should be replaced with a check that doesn't need to explicitly know about `MockSession`s at that location.
Another odd thing about the existing code is that it accesses and modifies `session._downloads` directly. Perhaps a better fix is to add a method like `Session.register_download()`.
Both of the proposed changes mentioned above are more invasive than this one, so it would be best to do them in a future PR, after things have settled down.
> Fix `render.download` in Shiny Express, take 2

- docs/_quartodoc-core.yml
- docs/_quartodoc-express.yml
This PR addes `reactive.extended_task` and `reactive.ExtendedTask` to the API reference index (under reactives and developer tools, respectively). The `reactive.ExtendedTask` is only shown in the Core docs, in line with the rest of the developer tools.
> docs: Add ExtendedTask to API index

- shiny/express/ui/_hold.py
This addresses one of the issues described in #1083.
> Update express.ui.hold() to accept any type of object

- shiny/ui/_navs.py
I noticed that many of the `navset_*` functions did not accept `MetadataNode` arguments, but they should, in case someone wants to pass in `HTMLDependency` objects.
For reference, the ability to accept `MetadataNode` args was added to many `navset_*` functions in #455, but some newer `navset_*` components did not have this typing.
> Update types to allow `navset_*` functions to accept `MetadataNode` args

- CHANGELOG.md
- shiny/express/_run.py
- shiny/input_handler.py
- shiny/module.py
- shiny/session/_session.py
- shiny/ui/_input_update.py
- tests/playwright/shiny/inputs/input_task_button2/app.py
- tests/playwright/shiny/inputs/input_task_button2/test_input_task_button2.py
Fixes #1107
The task button installs an input handler, which it uses to implement its auto-reset feature. One of the arguments to the input handler is the name/id of the input, a string. When a task button is in a module, that id string contains the module/namespace name as well.
Module-aware code in Shiny assumes regular strings are un-namespaced id's (akin to a relative path), and `ResolvedId` objects as namespaced id's (akin to an absolute path). In this case, we had a string that contained a namespaced id. That's then passed to `update_task_button`, which complains that it contains characters that shouldn't be part of an id.
This PR fixes the problem by changing the `input_handler` invoking code, changing the string id to a ResolvedId as early as possible.
> Fix input_task_button for modules

- CHANGELOG.md
- shiny/_main.py
- tests/pytest/asyncio_prevent.py
This addresses #1054. 
In some cases, `sys.stdout` and `sys.stderr` can be `None`, which would cause `sys.stderr.write()` to throw an error. This changes it to use `print(file=sys.stderr)`, which will not throw an error when `sys.stderr` is `None`.
From https://docs.python.org/3/library/sys.html#sys.__stderr__:
> Under some conditions stdin, stdout and stderr as well as the original values `__stdin__`, `__stdout__` and `__stderr__` can be `None`. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with **pythonw**.
> Replace `sys.stderr.write()` with `print(file=sys.stderr)`

- CHANGELOG.md
- shiny/render/_render.py
- shiny/session/_session.py
> bug(module): Do not use the module prefix in the `Renderer.output_id`

- shiny/_docstring.py
Related #1136 
Will close #1136 when posit-dev/py-shiny-site moves the submodule
> docs: Use all files within example folders for quartodoc

- CHANGELOG.md
- shiny/input_handler.py
- shiny/plotutils.py
- tests/playwright/shiny/inputs/input_task_button/app.py
> The method "utcfromtimestamp" in class "datetime" is deprecated
>    Use timezone-aware objects to represent datetimes in UTC; e.g. by calling .fromtimestamp(datetime.UTC) (reportDeprecated)
> chore: Remove deprecated datetime method calls

- CHANGELOG.md
- shiny/input_handler.py
- tests/playwright/shiny/bugs/0648-update-slider-datetime-value/test_update_slider_datetime_value.py
Followup to #1142 and #1143 
Fixes #1144 
```python
>>> datetime.fromtimestamp(1, tz = timezone.utc)
datetime.datetime(1970, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc)
>>> str(datetime.fromtimestamp(1, tz = timezone.utc))
'1970-01-01 00:00:01+00:00'
>>> pr = datetime.fromtimestamp(1, tz = timezone.utc).replace(tzinfo=None)
>>> pr
datetime.datetime(1970, 1, 1, 0, 0, 1)
>>> before = datetime.utcfromtimestamp(1)
datetime.datetime(1970, 1, 1, 0, 0, 1)
>>> str(pr)
'1970-01-01 00:00:01'
>>> before = datetime.utcfromtimestamp(1)
>>> str(before)
'1970-01-01 00:00:01'
```
> bug: Remove timezone info from `shiny.datetime` input handler

- Makefile
This PR re-organizes our `make check` target to perform the checks in the build workflow in GHA. It also creates `make check-fix` that fixes formatting issues instead of just checking them.
I also organized all of the check targets, e.g. `check-format`, `check-types`, `check-tests`, etc. leaving the existing well-known targets, e.g. `format`, `pyright`, `test`, etc.
The relevant public targets are now
```python
check                check code, style, types, and test (basic CI)
check-fix            check and format code, style, types, and test
pyright              check types with pyright
lint                 check style with flake8
test                 check tests quickly with the default Python
format               format code with black and isort
```
> chore(make): Update check and check-fix to replicate CI

- docs/_quartodoc-core.yml
- docs/_quartodoc-express.yml
Adds `ui.input_task_button()` and `ui.update_task_button()` to the reference index for Core and Express.
Also adds `update_action_button()` and `update_action_link()` to both indices.
> docs(input_task_button): Add to reference index, also update methods for action button/link

- Makefile
I thought it might be helpful if we had a `make docs` target in the top-level Makefile, since most people would expect to be able to build the docs from the root of `py-shiny`.
> chore(make): Add `make docs` and `make docs-preview`

- CHANGELOG.md
- shiny/ui/_navs.py
- tests/pytest/test_navs.py
Adds the missing `.bslib-gap-spacing` class to the `.nav-panel` container when it's fillable.
Fixes #1152
Try setting `fillable=True` and `fillable=False` in the example below
```python
from shiny import App, ui
app_ui = ui.page_navbar(
ui.nav_panel(
"Page 1",
ui.card("Card 1"),
ui.card("Card 2"),
),
sidebar=ui.sidebar("Foo"),
fillable=True,
title="foo",
)
app = App(app_ui, None)
```
> fix(nav_panel): Add `.bslib-gap-spacing` if nav panel is fillable

- .github/workflows/pytest.yaml
- examples/cpuinfo/app.py
- setup.cfg
- shiny/api-examples/download/app-core.py
- shiny/api-examples/download/app-express.py
- shiny/api-examples/download_button/app-core.py
- shiny/api-examples/download_button/app-express.py
- shiny/api-examples/download_link/app-core.py
- shiny/api-examples/remove_accordion_panel/app-core.py
- shiny/api-examples/remove_accordion_panel/app-express.py
- shiny/quarto.py
3.12 was officially release a few months ago, so we should be testing against it https://www.python.org/downloads/
> Add python 3.12 to test matrix

- shiny/ui/_accordion.py
- shiny/ui/_card.py
- shiny/ui/_html_deps_shinyverse.py
- shiny/ui/_input_check_radio.py
- shiny/ui/_input_task_button.py
- shiny/ui/_layout.py
- shiny/ui/_layout_columns.py
- shiny/ui/_navs.py
- shiny/ui/_page.py
- shiny/ui/_sidebar.py
- shiny/ui/_web_component.py
Closes #1159
This PR also brings the dependency handling closer to how we handle it in bslib (i.e., we have just one `components_dependencies()` that gets included whenever we need additional, component-specific, JS/CSS)
> Consolidate component dependency assets into a single dependency that gets included more generally

- .github/workflows/pytest.yaml
Prior to this change, we were running pytest, pyright, and flake8 twice in our GHA workflow, because `make check` runs all of those things, and we ran them individually above.
The reason that I did _not_ simply delete the others steps in the workflow and only keep `make check` is because if there is a failure in any one of the steps, a `make check` will exit without running subsequent steps. However, with the steps separate, and the `if:  steps.install.outcome == 'success' && (success() || failure())` condition that we have, it will run all of the check steps (assuming successful installation), even if one of the steps fails.
One more note: I don't really love that I added `make check-black; make check-isort` to the workflow, while the other steps are just `make test` and `make pyright`; …
> Remove redundant checks in GHA workflow

- CHANGELOG.md
- docs/_quartodoc-express.yml
- shiny/_app.py
- shiny/_utils.py
- shiny/express/__init__.py
- shiny/express/_mock_session.py
- shiny/express/_run.py
- shiny/reactive/_reactives.py
- shiny/render/_render.py
Closes #984. This PR does the following for Shiny Express apps:
- Automatically serves a `www` subdirectory, mounting it at `/`
- Adds a function `express.app_opts()`, which allows setting options that get passed to the `App()` constructor. This includes `static_assets` and `debug`.
And it adds this change for Shiny in general:
- In the `App()` constructor, the `static_assets` are now sorted by their mount point, from longest string to shortest before actually mounting them. This because previously, if an app had mounts `"/"` and `"/foo"`, specified in that order, it would never actually serve anything in the `"/foo"` mount because it would search the `"/"` mount first.
> Allow serving static assets in Shiny Express apps

- CHANGELOG.md
- shiny/_utils.py
- shiny/express/_run.py
Closes #1079.
For Shiny Express apps, this PR makes it so that if there is a `globals.py` file in the same directory as the app file, it will be loaded with the session context set to `None`.
Note that even if the user does not have an `import globals` statement in their app file, this will still run the code in `globals.py`. If they want to actually access the variables defined in that file, they will have to an import, as in `import globals`. The part of this that may be surprising is that the code in globals.py could execute even though it's not being referred to anywhere in the app code.
@jcheng5 It feels weird to me that `globals.py` would be executed simply because it's in the same directory as the app file, and that behavior could be surprising for users. Like, Imagine that …
> Automatically load `globals.py` for Express apps

- shiny/_app.py
- shiny/express/_run.py
This switches away from `os.PathLike[str]` to `Path`.  I'm not really sure why we used `os.PathLike[str]` in the first place, and it's not entirely clear to me what counts as `PathLike`, so I just went with `Path` to keep things simple.
If the user passes in a dictionary, it also allows the values to be strings, and not just `Path`s.
Previously, when the user passes in a dictionary, the code did not check if the paths were absolute, which could cause problems when running the application. (It only checked for absoluteness if the user passed in a string or Pathlike object.)
Now when a dictionary is passed in, it does check if those paths are absolute.
It also now prints a more useful error message if a path is not absolute:
```
ValueError: static_assets must be an absolute path: "foo". …
```
> Use more consistent types for `static_assets`

- shiny/_autoreload.py
- shiny/_hostenv.py
- shiny/_main.py
This PR makes Shiny detect that it's running on Codespaces, where the browser can't just point to `http://127.0.0.1:{autoreload-port}` and expect to succeed. Instead, a proxy URL is used. See [Forwarding ports in your codespace](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace).
Note that this alone is not enough to make autoreload work quite right on codespaces. The Shiny app will try to connect to the autoreload websocket server and fail. This is because Codespace's forwarded ports are private by default, and need you to access each proxy hostname via HTTP document load first so it can set some cookies and whatnot. A forthcoming PR for pyshiny-vscode will try to address this.
**Update:** Here's the corresponding pyshiny-vscode PR …
> Make autoreload work on codespaces

- examples/dataframe/app.py
- shiny/api-examples/data_frame/app-core.py
- shiny/api-examples/data_frame/app-express.py
- shiny/render/_dataframe.py
- tests/playwright/deploys/plotly/app.py
- tests/playwright/shiny/bugs/0676-row-selection/app.py
I am not certain about `<dataframe_renderer>.input_selected_rows()`. 
With the remaining work on data frames pushed into v0.9.0, I'm reverting this change so that we do not possibly revert it right after pushing it.
The behavior (in some form) will be restored in #1135 
Related: #1135
> Revert API changes made in `Selected rows method` #1121

- tests/playwright/shiny/bugs/0696-resolve-id/test_0696_resolve_id.py
Small change to a flaky test to ensure that the tested tooltip is always visible in the viewport.
> tests(resolve-id): Update window size to ensure tooltip is visible

- CHANGELOG.md
- setup.cfg
- shiny/_autoreload.py
> Remove asgiref run-time dependency

- CHANGELOG.md
- setup.cfg
The uvicorn and click packages are not needed when running on Emscripten.
> Remove uvicorn and click dependencies in Emscripten

- shiny/_autoreload.py
> Use `cast()` for asgiref types only when type checking

- docs/_quartodoc-express.yml
For the Express API docs, the `update_date` and `update_text` items point to the non-Express functions:
This PR fixes them, and it also simplifies the config file by removing `dynamic: true`, which I believe is no longer needed.
> Fix `express.ui.update_date` and`express.ui.update_text` links

- shiny/render/_render.py
> Better docs for `render.download`

- examples/airmass/app.py
I believe a recent release of `suntime` changed the expected input type of `get_sunrise_time()` and `get_sunset_time()`. https://github.com/SatAgro/suntime/releases/tag/v1.3.0
> Fix datetime input in airmass example app

- .github/workflows/pytest.yaml
- tests/playwright/conftest.py
> test: Resolve testing comments

- shiny/_app.py
Currently if you set
```python
app = App(app_ui, server, static_assets="www")
```
you'll get a helpful error message with two recommendations
```
ValueError: static_assets must be an absolute path: "www". Consider using one of the following instead:
os.path.join(__file__, "www")  OR  pathlib.Path(__file__).parent/"www"
```
Unfortunately, the first option isn't quite right 
```python
os.path.join(__file__, "www")
```
and will try to mount `/Users/person/path/to/app/app.py/www` instead of `/Users/person/path/to/app/www`.
The fix is to use
```python
os.path.join(os.path.dirname(__file__), "www")
```
> fix(static_assets): Need the directory containing the `app.py`, not the file itself

- CHANGELOG.md
- shiny/express/ui/_cm_components.py
- shiny/ui/_layout.py
- shiny/ui/_layout_columns.py
- shiny/ui/_valuebox.py
Pairs with https://github.com/rstudio/bslib/pull/1016
* Adds `min_height` to `ui.value_box()`
* Adds `min_height` and `max_height` to `ui.layout_columns()` and `ui.layout_column_wrap()`
> feat: ensure min/max height args on `value_box()` and column layouts

- shiny/session/_utils.py
From https://github.com/posit-dev/py-shiny/pull/1084#issuecomment-1915683032
> chore(get_current_session): Return default session if current is explicitly None

- setup.cfg
- shiny/_main.py
Addresses #1232.
When a user runs `shiny run app.py` on a Shiny Express app, this checks the version of the rsconnect-python package.
If (A) rsconnect-python is installed and (B), the version is less than 1.22.0, then this will print a message to stderr like this, and then it will run the app as usual.
```
Warning: rsconnect-python 1.21.0 is installed, but it does not support deploying Shiny Express applications. Please upgrade to at least version 1.22.0. If you are using pip, you can run `pip install --upgrade rsconnect-python
```
> For Express, emit message if need to upgrade rsconnect-python

- docs/_quartodoc-core.yml
Seems in the move to quartodoc, we lost documentation of these methods
https://shiny.posit.co/py/api/core/Session.html#shiny.Session
> Add back missing session methods

- docs/_quartodoc-core.yml
- tests/playwright/shiny/session/flush/test_on_flush.py
Related: #1236
Related: #1239 Sorry for merging it early! It was broken in the PR
cc @karangattu
> chore: Disable broken test on CI; Fix broken docs entries

- CHANGELOG.md
- shiny/ui/_bootstrap.py
> fix(panel_conditional): Include `.shiny-panel-conditional` class

- .github/py-shiny/pytest-browsers/action.yaml
- .github/workflows/build-docs.yaml
- .github/workflows/pytest.yaml
- .github/workflows/verify-js-built.yaml
- Makefile
- pytest.ini
Must run all browser (`chrome`, `firefox`, `webkit`) tests when merging to `main` (event: `merge_group`). However, within PRs, only `chrome` will be used (event: `pull_request`).
Related: 
* https://medium.com/@kojoru/how-to-set-up-merge-queues-in-github-actions-59381e5f435a
* https://github.blog/changelog/2022-08-18-merge-group-webhook-event-and-github-actions-workflow-trigger/
> test(CI): Add merge queue support for faster PR testing

- shiny/_main.py
- shiny/_template_utils.py
This PR adds another choice `shiny create` to choose from the [online gallery](https://shiny.posit.co/py/templates/)
And when chosen it opens your browser (along with a message)
> Add shiny create option to choose from online template gallery

- shiny/api-examples/panel_conditional/app-core.py
- shiny/api-examples/panel_conditional/app-express.py
The `panel_conditional` examples are broken as can be seen in the [doc](https://shiny.posit.co/py/api/core/ui.panel_conditional.html) (the elements are always shown whatever the condition's value):
This is simply caused by the same id "slider" being used both for the `input_select` and the `input_slider`. Using different ids fixes the issue:
> Fix panel_conditional examples

- shiny/render/_data_frame_utils/_unsafe.py
- tests/playwright/shiny/components/data_frame/edit/app.py
cc @karangattu 
Ex: Column type is `string` (not unknown) for 
```python
df["Sample Number"] = df["Sample Number"].apply(
lambda x: ui.HTML(str(ui.tags.strong(ui.tags.em(str(x)))))
```
> feat(data frame): If a column is marked as `str`, make sure it is not `HTML`

- shiny/express/__init__.py
- shiny/express/_mock_session.py
- shiny/express/_module.py
- shiny/render/renderer/_renderer.py
- shiny/session/_utils.py
Example:
```python
from counter import counter
counter("one")
ui.hr()
counter("two")
```
```python
from shiny import reactive
from shiny.express import module, render, ui
@module
def counter(input, output, session, starting_value=0):
count = reactive.value(starting_value)
ui.input_action_button("btn", "Increment")
with ui.div():
@render.express
def current_count():
count()
@reactive.effect
@reactive.event(input.btn)
def increment():
count.set(count() + 1)
```
> Modules for Shiny Express

- shiny/express/_module.py
- shiny/render/renderer/_renderer.py
This PR fixes some typing issues introduced by #1220 and by pyright 1.1.359.
> Fix typing issues

- tests/playwright/utils/deploy_utils.py
Currently we swallow exceptions in order for secrets to not show up in the logs when a test fails.
If GitHub Actions proactively scrubs the secrets from the logs, we do not need this exception swallower step since it can make debugging deploys failure harder and only way to get around it is run those tests locally.
Verified it by intentionally causing the deploys to fail and checking the logs from GitHub Actions - 
```sh
subprocess.CalledProcessError: Command 'rsconnect content search --server None --api-key *** --title-contains express_page_sidebar' returned non-zero exit status 1.
```
> test: remove exception swallower to make debug easier

- Makefile
This reverts commit 2a19d8daee8565a6c4c7f316b2fd140088476f89.
Request: https://github.com/posit-dev/py-shiny/pull/1302#issuecomment-2050953967
Merge requirements:
> test(deploy): Revert pinned `rsconnect` version in #1302

- CHANGELOG.md
- shiny/ui/_html_deps_external.py
Adds `all_files=True` to the Bootstrap dependency so that the font files in the base Bootstrap theme are correctly included in the dependency. Without this, `font.css` and the font files aren't available in the browser but show up in `bootstrap.min.css`.
Noticed in https://github.com/posit-dev/py-shiny-site/pull/140.
> fix(bootstrap): Include all files

- shiny/session/_session.py
Closes #1355. 
Seems it was an oversight in #907 that for `SilentOperationInProgressException`, we _don't_ want the `recalculated` message to be sent upon exit. For reference, that's what we do on the R side:
https://github.com/rstudio/shiny/blob/ecb591f/R/shiny.R#L1197-L1226
Note that this PR will unblock #1353, and hence #918 as well
> Stop sending recalculated message immediately after persistent progress message

- shiny/_utils.py
Pyright 1.1.362 made some changes which resulted in new type errors. The `cast`s here work around those errors.
> Add casts for coro to help pyright

- setup.cfg
- shiny/express/_stub_session.py
- shiny/reactive/_reactives.py
- shiny/session/_session.py
- tests/playwright/examples/example_apps.py
- tests/pytest/test_poll.py
Previously, busy/idle messages were sent for each output/effect. That isn't correct, those messages are only supposed to be sent when the session as a whole becomes busy/idle.
Fixes #1379
> Send busy/idle at the right times

- shiny/ui/_input_select.py
This updates the type annotation for `input_selectize(options=)` where dictionary values can be `Jsonifiable` objects.
This doesn't affect behavior, just removes the red squiggle on apps like this
```python
from shiny.express import input, render, ui
ui.input_selectize(
"filter",
"Filter by",
choices={
"": "",
"first": "First Choice",
"second": "Second Choice",
},
options={
"plugins": ["clear_button"]
},
)
@render.text
def txt():
if input.filter():
return f"Data is filtered by your {input.filter()} choice."
else:
return "The data is not fitered."
```
> fix(selectize): Accept jsonifiable values in `options` dictionary

- shiny/_main.py
Adds support for `--version` to return the version of `shiny`:
```
❯ shiny --version
shiny, version 0.9.0.9000
```
Fixes #1385
> feat(cli): Add `shiny --version`

- shiny/reactive/_reactives.py
- shiny/session/_session.py
- tests/pytest/mocktime.py
Fixes #1381
During a synchronous phase of the event loop, we can build up network messages that need to get to the client. Because writes are naturally async, we do some weird stuff to semi-execute them which usually but doesn't always succeed. In the case where the write doesn't succeed, they're held at least until the next time the current task yields; before this commit, that could be a long time indeed, if the app is written synchronously (as about 100% of Shiny apps are).
This change yields to the event loop after invalidating the session, which gives the writes a chance to complete. This should take care of the observed problem of progress messages not making it (issue #1381). It also yields after each successful `@effect`, in case insert_ui, custom messages, etc. were sent during …
> Yield to give "synchronous" writes a chance to complete

- setup.cfg
- tests/playwright/shiny/components/busy_indicators/app.py
- tests/playwright/shiny/components/busy_indicators/test_busy_indicators.py
Add tests to verify spinner and pulse busy indicators are working as expected.
Also included is a test app that allows user to switch between `spinner` and `pulse` busy indicators
Make changes in `setup.cfg` to make sure users have recent version of playwright to ensure up-to-date browsers for playwright testing.
> Add busy indicator tests

- tests/playwright/deploys/express-accordion/test_deploys_express_accordion.py
- tests/playwright/deploys/express-dataframe/test_deploys_express_dataframe.py
- tests/playwright/deploys/express-folium/test_deploys_express_folium.py
- tests/playwright/deploys/express-page_default/test_deploys_express_page_default.py
- tests/playwright/deploys/express-page_fillable/test_deploys_express_page_fillable.py
- tests/playwright/deploys/express-page_fluid/test_deploys_express_page_fluid.py
- tests/playwright/deploys/express-page_sidebar/test_deploys_express_page_sidebar.py
- tests/playwright/deploys/plotly/test_plotly_app.py
- tests/playwright/deploys/shiny-client-console-error/test_shiny_client_error.py
- tests/playwright/utils/deploy_utils.py
Add reruns to the deploy tests since the deploy tests intermittently fail with building image on `shinyapps.io`.
> bug(test-deploy): Add retries for deploy tests

- tests/playwright/shiny/components/busy_indicators/app.py
- tests/playwright/shiny/components/busy_indicators/test_busy_indicators.py
Tests were failing since the pulse busy indicator had not started before we started assertions.
Now we verify computations have stopped before we do assertions.
> fix: Add wait till pulse animation has started

- shiny/_main.py
Fixes #1373
There's a general problem in Shiny for Python where we start asynchronous writes to network connections, but then call code written by the Shiny app author which may block for arbitrary lengths of time, without yielding to the Python event loop. This puts us a little outside of the sweet spot of Python async (ideally you'd just not be blocking the main thread very often).
With asyncio, we generally get away with this because the kinds of messages we send without yielding are generally pretty small, and they get sent immediately. What we observed with uvloop is that it doesn't really attempt to do anything about theses writes until you yield. So the fix in this PR makes it so we never use uvloop for Shiny.
This issue is harder to repro than it was because of #1388, which is …
> Don't use uvloop

- CHANGELOG.md
- examples/dataframe/app.py
- shiny/render/_data_frame.py
- tests/playwright/shiny/bugs/0676-row-selection/app.py
- tests/playwright/shiny/bugs/1345-render-data-frame-input/app.py
- tests/playwright/shiny/components/data_frame/edit/app.py
- tests/playwright/shiny/components/data_frame/html_columns_df/df_organization/app.py
- tests/playwright/shiny/components/data_frame/html_columns_df/df_organization/test_df_organization.py
- tests/playwright/shiny/components/data_frame/row_selection/app.py
This approach should also be applied in #1374 .
> api!: Rename `.input_cell_selection()` to `.cell_selection()`

- docs/Makefile
- setup.cfg
This PR fixes `make docs`
<details>
<summary>Thanks to some help from @machow:</summary>
Hmmm... debugging with
```
from quartodoc import get_object
get_object("shiny:ui.page_sidebar", dynamic=True)
```
When I go up and print out the griffe object trying to get ui, I see this:
```
ipdb> !self
Module([PosixPath('/Users/machow/repos/py-shiny/venv/bin/shiny')])
```
But I feel like that's not the right path for shiny. I wonder if there's some kind of venv thing that's putting this path too early or something... here's my sys.path
```
['/Users/machow/repos/py-shiny/venv/bin', '/Users/machow/.pyenv/versions/3.12.3/lib/python312.zip', '/Users/machow/.pyenv/versions/3.12.3/lib/python3.12', '/Users/machow/.pyenv/versions/3.12.3/lib/python3.12/lib-dynload', '', …
```
> Fix API reference generation (quartodoc)

- docs/_quartodoc-express.yml
- shiny/api-examples/express_module/app-express.py
- shiny/express/_module.py
- shiny/express/_stub_session.py
This fixes a problem with using modules in Shiny Express. Prior to the change, this app would raise an error; after the change, it works:
```py
from shiny import reactive
from shiny.express import module, render, ui
@module
def counter(input, output, session, starting_value: int=0):
count = reactive.value(starting_value)
ui.input_action_button("btn", "Increment")
with ui.div():
@render.express
def current_count():
count()
@reactive.effect
@reactive.event(input.btn)
def increment():
count.set(count() + 1)
counter("one")
ui.hr()
counter("two")
```
> In ExpressStubSession, set 'app' and 'id'

- shiny/express/_run.py
Fixes:
* Remove extra param `type_ignores` from `ast.Interactive` call
* Added in https://github.com/posit-dev/py-shiny/pull/767/files#diff-8c4d6194dce915462e220ab012cb9a00199777d2176077a7b5669215009a0e67R142. 
* Not found in type definition: https://docs.python.org/3/library/ast.html#ast.Interactive
> `class ast.Interactive(body)`
* But is found in `ast.Module` in lines above
> `class ast.Module(body, type_ignores)`
> chore(CI): Fix failing CI tests

- .github/workflows/build-docs.yaml
Related: https://github.com/posit-dev/shinylive/blob/144a5de66cc198044c918df9d786e92804d9ff25/Makefile#L94C4-L94C20
Related: https://github.com/posit-dev/shinylive/pull/136
> bug(CI): Only update the shiny submodule when making the dev docs

- examples/dataframe/app.py
- examples/express/accordion_app.py
- examples/express/basic_app.py
- examples/express/hold_app.py
- examples/express/shared_app.py
- examples/headers/app.py
- examples/moduleapp/app.py
- examples/typed_inputs/app.py
This PR updates examples to switch from `output_text_verbatim` and `render.text` to `output_code` and `render.code`.
> Use `output_code()` and `render.code()`

- setup.cfg
Our CI is currently failing since Python 3.12 no longer pre-installs setuptools in virtual environments created with venv.
https://docs.python.org/3/whatsnew/3.12.html
> Add setuptools as an install requirement in Python 3.12 and above

- .vscode/extensions.json
We've moved the `Posit.shiny-python` extension to `Posit.shiny`. 
See https://shiny.posit.co/blog/posts/shiny-vscode-1.0.0/ for more details about the updates in this release.
> chore: update shiny-vscode extension ID

- Makefile
`make dist` (which is required for `make install`) currently assumes it has setuptools, but that is no longer the case with Python 3.12.
Related #1435
> `make install` shouldn't assume it has `setuptools`

- CHANGELOG.md
- shiny/express/_run.py
This closes #1440.
I was able to reproduce the problem on a Connect server, and then test that it was fixed with this change.
> Resolve path to file when running Shiny Express apps

- Makefile
Seen in https://github.com/posit-dev/py-shiny/actions/runs/9353228742/job/25743310548
> bug(CI): Quote `TEST_FILE` usage to avoid args leaking

- setup.cfg
Related: https://github.com/microsoft/pyright/issues/8087
> chore(lint): Set pyright version to 1.1.365 to avoid error in 3.12 checks

- CHANGELOG.md
- shiny/playwright/__init__.py
- shiny/playwright/controls/_controls.py
- tests/playwright/shiny/components/card-input/test_card-input.py
- tests/playwright/shiny/components/value_box/kitchensink/test_valuebox_ks.py
- tests/playwright/shiny/components/value_box/smoke/test_valuebox.py
- tests/playwright/shiny/experimental/card/kitchensink/test_card_ks.py
- tests/playwright/shiny/experimental/card/test_card.py
- tests/playwright/shiny/outputs/test_output_image.py
- tests/playwright/shiny/outputs/test_output_plot.py
- tests/playwright/shiny/plot-sizing/test_plot_sizing.py
Add changelog entry for #1448
Add documentation for classes and methods under controls.py
> docs(testing): Add documentation for all public testing methods

- setup.cfg
- shiny/plotutils.py
Related: https://github.com/numpy/numpy/pull/24376 ; (Removes `np.NaN` for v2.0.0 release)
> chore: Use `np.nan` instead of `np.NaN`

- tests/playwright/deploys/plotly/rsconnect-python/plotly.json
- tests/playwright/deploys/plotly/test_plotly_app.py
The shinyapps.io deploy test for the `plotly` app was failing because of some issue with the existing app on shinyapps.io.
When navigating to the url, the app was stuck loading.
The solution was to delete that app and use a different app id which is reflected in the changes.
> fix(test): Fix failing shinyapps.io deploy test

- setup.cfg
- shiny/render/transformer/_transformer.py
Related: https://github.com/posit-dev/py-shiny/pull/1459
> chore(pyright): Remove version restriction and fix appropriate pyright errors

- docs/_quarto.yml
Currently https://posit-dev.github.io/py-shiny/docs/api/test/index.qmd is broken because it refers to `../api/test/index.qmd` instead of `../api/testing/index.qmd`
> fix(docs): Update path to reflect correct one

- shiny/reactive/_core.py
This fixes an issue that is flagged by pyright 1.1.369.
> Add return type for `_task()`

- shiny/http_staticfiles.py
When a shiny app is running under a prefix (root_path in ASGI terms), the static files are not served correctly under pyodide. This is because the ASGI path includes the root_path, and the root_path should be removed.
Starlette 0.33 and 0.34 however, did not set root_path correctly, and in those cases, we have to rely on route_path.
Related discussions:
https://github.com/encode/starlette/pull/2400
https://github.com/encode/starlette/discussions/2361
A related fix we had in Solara:
https://github.com/widgetti/solara/pull/413/
But this fix also did not seem to work for our situation at https://py.cafe
I logged the output of the relevant entries in the scope dict, together with the starlette version:
```
starlette 0.32.0 {'path': '/strftime-min.js', 'root_path': '/_app/lib/strftime-0.9.2'} …
```
> fix: support static files on pyodide / py.cafe under a prefix

- CHANGELOG.md
- shiny/pytest/_fixture.py
Use approach that allows for dynamic path resolution based on runtime conditions
> fix(tests): dynamically determine the path to the shiny app

- shiny/render/__init__.py
- shiny/render/_data_frame_utils/__init__.py
- tests/playwright/shiny/components/data_frame/styles/app.py
> bug(data frame): Export `render.StyleInfo`

- shiny/ui/_theme.py
Needed to use `__file__` and absolute pathing for the example to be copy, paste, runnable.
> docs(Theme): Fix example and clarify usage

- shiny/ui/_layout_columns.py
In Python <= 3.9, the following code throws an error
```python
from typing import Union
if isinstance(1, Union[int, str]):
print("yes")
#> TypeError: Subscripted generics cannot be used with class and instance checks
```
We have a variant of this with `CssUnit = int | float | str` in `ui.layout_columns()`. This is fixed by using `isinstance_cssunit()`, an existing helper function created just for this scenario.
> fix(layout_columns): Fix coercion of scalar row height to list for python <= 3.9

- shiny/ui/_chat_normalize.py
- tests/playwright/shiny/components/chat/append_user_msg/app.py
- tests/playwright/shiny/components/chat/append_user_msg/test_chat_append_user_msg.py
This was resulting in error even though it shouldn't be:
```python
from shiny import reactive
from shiny.express import render, ui
chat = ui.Chat(id="chat")
chat.ui()
@reactive.effect
async def _():
await chat.append_message({"content": "A user message", "role": "user"})
```
> Follow up to #1453: allow user roles when normalizing a dictionary

- shiny/ui/_chat.py
In anticipation of #793, where we'll be removing the `session` parameter from functions that must be called inside a session context.
> Remove session parameter from `ui.Chat()`

- examples/chat/enterprise/aws-bedrock-anthropic/app.py
- examples/chat/enterprise/aws-bedrock-anthropic/app_utils.py
- examples/chat/enterprise/aws-bedrock-anthropic/requirements.txt
- examples/chat/enterprise/azure-openai/app.py
- examples/chat/enterprise/azure-openai/app_utils.py
- examples/chat/enterprise/azure-openai/requirements.txt
- examples/chat/hello-providers/anthropic/app.py
- examples/chat/hello-providers/anthropic/app_utils.py
- examples/chat/hello-providers/anthropic/requirements.txt
- examples/chat/hello-providers/gemini/app.py
- examples/chat/hello-providers/gemini/app_utils.py
- examples/chat/hello-providers/gemini/requirements.txt
- examples/chat/hello-providers/langchain/app.py
- examples/chat/hello-providers/langchain/app_utils.py
- examples/chat/hello-providers/langchain/requirements.txt
- examples/chat/hello-providers/ollama/requirements.txt
- examples/chat/hello-providers/openai/app.py
- examples/chat/hello-providers/openai/app_utils.py
- examples/chat/hello-providers/openai/requirements.txt
- pyrightconfig.json
This makes the `app.py` file for the `Chat` examples a bit more readable, and also doesn't crash the app if `{dotenv}` isn't installed.
> Follow up to #1508: move dotenv complexity to `app_utils.py` module

- .github/workflows/deploy-tests.yaml
- .github/workflows/pytest.yaml
We want to only run the **Deploy pre-checks** on every commit in a PR.
We will separate the deploy tests into its own workflow file from `pytest.yaml`
> tests(deploys): separate deploy test workflow from pytest workflow

- CHANGELOG.md
- shiny/playwright/controller/_controls.py
- shiny/render/_data_frame.py
- shiny/render/_data_frame_utils/__init__.py
- shiny/render/_data_frame_utils/_html.py
- shiny/render/_data_frame_utils/_pandas.py
- shiny/render/_data_frame_utils/_patch.py
- shiny/render/_data_frame_utils/_tbl_data.py
* `.cell_patches()` now has type: `list[CellPatch]` (from `list[CellPatchProcessed]`)
* `.data_view()` now contains the original result of the CellPatch, not the value that has been processed by the session.
This will result in the `session` processing duplicate values, but we can fix that bridge when we get there if its a problem.
> bug(data frame): Reduce usage of `CellPatchProcessed` in favor of `CellPatch`

- CHANGELOG.md
- shiny/ui/fill/_fill.py
> fix(remove_all_fill): copy `tag` before modifying it

- shiny/ui/_chat.py
- tests/pytest/test_chat.py
For Anthropic, the first message in a chat must have `"role": "user"`; otherwise the API will return an error.
This PR ensures that when the messages are trimmed, the first message is a `user` message.
One possibly confusing thing: Suppose you initialize the chat with something like this:
```py
chat = ui.Chat(
"chat",
messages=[
{"role": "assistant", "content": "Arrgh! I am a chatbot that speaks like a pirate. How may I help ye?"},
],
)
```
Then when the user enters a message and the messages get sent to the LLM, this first message will get trimmed off, and so the LLM will not know that it's supposed to respond like a pirate. The problem is that the app author won't have any indication that this first message is getting trimmed, so if they expect anthropic to behave like openai (where the …
> Ensure first message is user message for anthropic

- setup.cfg
Originally added in https://github.com/posit-dev/py-shiny/pull/1502/files#diff-edcbc472de7b775474e270c5dbdd2f1d942ed49635d21677717847f0d50b5013R50
> bug: Set min version of typing-extensions to 4.10.0 for `TypeIs` support

- CHANGELOG.md
- examples/dataframe/app.py
- examples/duckdb/app.py
- examples/duckdb/requirements.txt
- setup.cfg
- shiny/__init__.py
- shiny/api-examples/todo_list/app-core.py
Will fix newly broken playwright tests
> Require shinyswatch 0.7.0 and update examples accordingly

- tests/playwright/shiny/components/chat/append_user_msg/test_chat_append_user_msg.py
- tests/playwright/shiny/components/chat/basic/test_chat_basic.py
- tests/playwright/shiny/components/chat/errors/test_chat_errors.py
- tests/playwright/shiny/components/chat/stream/test_chat_stream.py
- tests/playwright/shiny/components/chat/transform/test_chat_transform.py
- tests/playwright/shiny/components/chat/transform_assistant/test_chat_transform_assistant.py
- tests/playwright/utils/deploy_utils.py
No clue why they are not working but they fail too often to maintain them
Related #1565
> chore(ci): Skip all chat tests on webkit

- shiny/api-examples/nav_control/app-core.py
- shiny/api-examples/nav_control/app-express.py
- shiny/api-examples/nav_menu/app-core.py
- shiny/api-examples/nav_menu/app-express.py
- shiny/api-examples/nav_spacer/app-core.py
- shiny/api-examples/nav_spacer/app-express.py
- shiny/api-examples/navset_bar/app-core.py
- shiny/api-examples/navset_bar/app-express.py
- shiny/api-examples/navset_card_pill/app-core.py
- shiny/api-examples/navset_card_pill/app-express.py
- shiny/api-examples/navset_card_tab/app-core.py
- shiny/api-examples/navset_card_tab/app-express.py
- shiny/api-examples/navset_card_underline/app-core.py
- shiny/api-examples/navset_card_underline/app-express.py
- shiny/api-examples/navset_pill/app-core.py
- shiny/api-examples/navset_pill/app-express.py
- shiny/api-examples/navset_pill_list/app-core.py
- shiny/api-examples/navset_pill_list/app-express.py
- shiny/api-examples/navset_tab/app-core.py
- shiny/api-examples/navset_tab/app-express.py
- shiny/api-examples/navset_underline/app-core.py
- shiny/api-examples/navset_underline/app-express.py
- shiny/express/ui/_cm_components.py
- shiny/ui/_navs.py
Add examples of the following for both `core` and `express` function reference page
- navset_bar
- navset_card_pill
- navset_card_tab
- navset_card_pill
- navset_card_tab
- navset_card_underline
- navset_pill
- navset_pill_list
- navset_underline
- nav_menu
- nav_control
- nav_spacer
> docs(navset): Add examples for navset

- shiny/_docstring.py
This is an attempt to address the issue in https://github.com/posit-dev/py-shiny-site/issues/181#issuecomment-2256243005.
> Fix logic for detection of support files in docs

- CHANGELOG.md
- shiny/ui/_notification.py
Working on R side: [shinylive link](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAZwAsBLCATwEF0AKAHQgAIeBXejwC8PAGYAbQQBMAClADmcLrz48oBUvRIAhfqVIkuNWkQDunPD0sBlUxbABKbn0e4XPanABOANx8i4vwQmtoQ7Iyo+rg8RPpRpI48IB58RABGXn5wAKL+ZBEQCQAkdOYxKapqnvYAckRaYvQEUFpGlgCycNTUinA85AAepJbuVdXqoSSBUOy03nBigZYAVlC+UNQE3vSopIgSRC1tEBgLh1DS7I4A3KPWYFhwF9I8qH2WbqkTP7980vxvK0woFagBVAAyEO+rm+AF9nKo4dxHGA4QBdIA)
Reprex app: [shinylive link](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmSYBXDgB0ISjgHMIUuEwC8cjhg1kONDoShHSAfXbEA7gAolTZ0wVgAKp1E3ZAGwAmTIZM-hwsaKhwUHRMUDQUMQCsLACEbnhOLmTYkdpucHQMdOmZzv6ydOYcpNoAcqRwGRAAlEoqElIyAFYspG0Qglxk9j2kGOUSLPbA9RBwALrNrRBgAL7zQA)
```python
ignore …
```
> bug(notification): Allow for duration to be `None` and passed to client

- CHANGELOG.md
- shiny/ui/_chat.py
- tests/playwright/shiny/components/chat/module/app.py
- tests/playwright/shiny/components/chat/module/test_chat_module.py
> Get `ui.Chat()` working inside Shiny modules

- shiny/render/_data_frame_utils/_datagridtable.py
Fixes https://github.com/posit-dev/py-shiny/issues/1591
> docs: Update note on style keys allowing for kebab-case

- shiny/ui/_theme.py
Added double-quotes around `shiny[theme]`... code formatter switched from double-quotes to single-quotes in the Python code section; escaping not necessary in the docstring as it's already a triple-quote string.
Fixes #1603
> docs: Add double-quotes to shiny[theme]

- CHANGELOG.md
- shiny/ui/_chat_provider_types.py
> Make sure `Chat.messages(format='google')` converts role assistant -> model

- setup.cfg
See https://github.com/syrupy-project/syrupy/issues/879
> Pin syrupy to avoid pytest-rerunfailures incompatibility

- shiny/http_staticfiles.py
Not sure what is triggering this but it's happening intermittently for both @cpsievert and myself.
Not sure why Content-Type would ever be missing, much less intermittently.
Edit: This happens when the server returns `304 Not Modified`... makes sense.
> Fix KeyError when serving static files

- Makefile
- docs/_renderer.py
- pyproject.toml
Griffe v1 moved some things around
> Quartodoc 0.7.6

- pytest.ini
Related: https://github.com/pytest-dev/pytest-asyncio/commit/c74d1c3fba1afac0b8316763257c915bfba5f5e3
> ci(remove future behavior warning): Set the `asyncio_default_fixture_loop_scope` to `fixture`

- Makefile
- tests/playwright/utils/deploy_utils.py
* Better stderr/stdout output for #1658 
* Fix bug where `make playwright-deploys` was testing all playwright tests, not just `./playwright/deploys` tests
> CI(debug): Print full stdout/stderr when command fails

- CHANGELOG.md
- shiny/_main_create.py
Rather than use the template's directory name, we should be using the `template.id` for the default directory in `shiny create`.
```bash
❯ shiny create
? Which template would you like to use? Basic app
… Creating Basic app Shiny app...
? Enter destination directory: ./01-basic-app
```
```bash
❯ shiny create
? Which template would you like to use? Basic app
… Creating Basic app Shiny app...
? Enter destination directory: ./basic-app
```
> fix(shiny create): Use `template.id` for default directory

- CHANGELOG.md
- shiny/ui/_chat.py
At least a couple times now, I've encountered situations where `.append_message_stream()` was failing to raise/report errors that occur inside of it. Here is the most recent example I came across:
```python
import litellm
chat = ui.Chat(id="chat")
chat.ui()
@chat.on_user_submit
async def _():
messages = chat.messages()
response = litellm.completion(model="gpt-4o", messages=messages, stream=True)
await chat.append_message_stream(response)
```
It turns out that, in this case, the effect that listens to and reports errors in the streaming task (`_handle_error`) gets invalidated before the effects gets a chance to run. In hindsight, this is an obvious mistake in the original implementation, and it'd be much better to cleanup the effect only after it runs.
With …
> Destroy `.append_message_stream()`'s error reporting effect only after it gets a chance to run

- tests/playwright/examples/test_examples.py
- tests/playwright/shiny/components/data_frame/pandas_compatible/test_df_pandas_compatible.py
- tests/playwright/utils/deploy_utils.py
- tests/pytest/_utils.py
Error when trying to run `./examples/airmass/app.py`:
```
import astropy.units as u
File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/astropy/units/__init__.py", line 23, in <module>
from .quantity import *
File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/astropy/units/quantity.py", line 36, in <module>
from .quantity_helper import can_have_arbitrary_unit, check_output, converters_and_unit
File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/astropy/units/quantity_helper/__init__.py", line 16, in <module>
from . import erfa, function_helpers, helpers, scipy_special
File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/astropy/units/quantity_helper/function_helpers.py", line 79, in <module>
np.prod, …
```
> test: Add skip for airmass example on python 3.9

- .github/py-shiny/pytest-browsers/action.yaml
- tests/playwright/conftest.py
- tests/playwright/playwright-pytest.ini
We want to remove video for debugging test failures on GitHub Actions since most debugging seems to happen locally and enabling that feature means we cannot use the same page for the duration of the session making our runs slower.
> tests(video): Revert to page fixture that exists per session (not just function)

- CHANGELOG.md
- shiny/ui/_theme.py
Fixes #1681
We are currently relying on `os.path.join()` and `os.path.realpath()` which is usually the right choice, but because we're putting the path into another string, we need better escaping for path separators (or better path separators).
The new approach is to use `Path(path).as_posix()` to convert `c:\mydir\...\_01_functions.scss` to `c:/mydir/.../_01_functions.scss`, which then drops into the Sass strings easily.
The code below was run on Windows 11, where the problem is reproducible and highlights the core issue.
```python
from shiny.ui._theme import path_pkg_preset
import sass
import os
from pathlib import Path
path_functions = path_pkg_preset("shiny", "_01_functions.scss")
path_functions
#> 'C:\\Users\\garrick\\Documents\\external\\shiny_css_compilation_demo\\.venv\\Lib\\site- …
```
> fix: Use posix paths in import statements in Sass strings

- Makefile
- shiny/ui/_chat.py
- shiny/ui/_chat_normalize.py
- shiny/ui/_chat_types.py
- tests/playwright/shiny/components/chat/transform_assistant/app.py
- tests/playwright/shiny/components/chat/transform_assistant/test_chat_transform_assistant.py
In anticipation of https://github.com/posit-dev/py-htmltools/pull/86
> Anticipate `htmltools.HTML` no longer inheriting from `str`

- .github/py-shiny/check/action.yaml
- .github/workflows/pytest.yaml
- shiny/ui/_navs.py
- tests/pytest/test_modules.py
Related to #1690 and posit-dev/py-htmltools#86
Adds a new `check` action to check the local py-shiny. Note, the py-shiny repo is NOT going to utilize it as the formatting of the job steps is not ideal. However, it is good enough for htmltools' testing.
> chore: Add types and check action for py-htmltools

- shiny/types.py
- shiny/ui/_navs.py
The nav panel value is currently given as a `str`. I believe we should not allow for it to be an `HTML()` object. 
So, keeping the types as `str`, the final retrieved attribute value should be str (and not `HTML()`). If there somehow happens to have an HTML value, we will convert it to a str at retrieval time
Related #1692
> chore: More minor type changes in prep for py-htmltools updates

- pyproject.toml
- tests/pytest/test_chat.py
`langchain_core` was updated to 0.3.2 on Sep 19th, and errors started popping up on Sept 20th 
Error being seen in CI:
```
=================================== FAILURES ===================================
__________________________ test_as_langchain_message ___________________________
[gw0] linux -- Python 3.12.6 /opt/hostedtoolcache/Python/3.12.6/x64/bin/python3
def test_as_langchain_message():
from langchain_core.language_models.base import LanguageModelInput
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import (
AIMessage,
BaseMessage,
HumanMessage,
MessageLikeRepresentation,
SystemMessage,
)
from shiny.ui._chat_provider_types import as_langchain_message
assert BaseChatModel.invoke.__annotations__["input"] == "LanguageModelInput" …
```
> chore: Fix `langchain_core` test that used a new `Sequence` type

- tests/playwright/examples/test_examples.py
> chore: revert check where airmass skips on python 3.9

- .github/workflows/pytest.yaml
- pyproject.toml
Full changes will come in #1711 
Related reasoning `py-htmltools` dropped py3.8 support due to bad typing support (and the python version is EOL as of next week): https://github.com/posit-dev/py-htmltools/commit/c5083e04ab40071b317fcc935a096a2e3a14aec1#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L21
> chore: Drop testing of python 3.8 (incomplete)

- pyproject.toml
- shiny/render/_data_frame_utils/_types.py
- tests/playwright/shiny/components/data_frame/data_view_info/app.py
- tests/playwright/shiny/components/data_frame/df_methods/app.py
- tests/playwright/shiny/components/data_frame/row_selection/app.py
- tests/playwright/shiny/components/data_frame/styles/app.py
- tests/playwright/shiny/components/data_frame/validate_column_labels/app.py
- tests/pytest/test_render_data_frame_tbl_data.py
Hey - as discussed in https://github.com/posit-dev/py-shiny/pull/1570, a blocker to not upper-bounding Narwhals was that `dtypes` and `typing`  weren't available in `narwhals.stable.v1`
We have now:
- made a release which includes them
- added a downstream test in the Narwhals CI which checks that the `py-shiny` test suite + type checking keeps working on every commit
so I'd like to suggest removing the upper-bound
Thanks again for the collaboration here, it's been very rewarding to see this happen! 🤗
> build: set Narwhals 1.9.1 as minimum, remove upper bound, use narwhals.stable.v1 for dtypes and typing

- pyproject.toml
- shiny/_utils.py
- tests/playwright/shiny/components/data_frame/edit/app.py
- tests/playwright/shiny/components/data_frame/styles/great_tables_test_utils.py
- tests/playwright/shiny/deprecated/output_transformer/app.py
- tests/playwright/shiny/server/output_transformer/app.py
- tests/pytest/test_output_transformer.py
Errors being seen in #1720 (and other PRs)
> ```
> -------- Checking types with pyright --------
> pyright
> /home/runner/work/py-shiny/py-shiny/tests/playwright/shiny/components/data_frame/edit/app.py
>   /home/runner/work/py-shiny/py-shiny/tests/playwright/shiny/components/data_frame/edit/app.py:92:30 - error: Condition will always evaluate to False since the types "Loc" and "Literal['data']" have no overlap (reportUnnecessaryComparison)
> /home/runner/work/py-shiny/py-shiny/tests/playwright/shiny/components/data_frame/styles/great_tables_test_utils.py
>   /home/runner/work/py-shiny/py-shiny/tests/playwright/shiny/components/data_frame/styles/great_tables_test_utils.py:26:30 - error: Condition will always evaluate to False since the types "Loc" and "Literal['data']" have no overlap …
```
> chore(pyright): Unlock pyright version with minimum at `1.1.383`

- README.md
Fixes #1720
`pip install https://github.com/posit-dev/py-shiny/tarball/main`
was causing errors during install.
The error message mentions:
```
For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```
running `pip install git+https://github.com/posit-dev/py-shiny.git` seem to work
see #1720 for more details.
> chore(docs): Update dev install instructions

- .github/workflows/pytest.yaml
- Makefile
> bug(ci): Split narwhals integration command into two commands

- CHANGELOG.md
- shiny/render/_render.py
Fixes https://github.com/posit-dev/py-shiny/issues/1724
> bug(download): Properly namespace output_id for render.download in modules

- examples/penguins/app.py
- examples/static_plots/app.py
- shiny/render/_data_frame.py
- shiny/render/_render.py
Mental followup PR to https://github.com/posit-dev/py-shiny/issues/1724 
(only) Fixed some inconsistent variable names.
> chore: Cosmetic code changes

- shiny/ui/_chat.py
Follow up to #1736: fixes markup generation for user startup messages:
```python
chat = ui.Chat(id="chat")
chat.ui(
messages=[
{"content": "Foo", "role": "assistant"},
{"content": "Bar", "role": "user"},
{"content": "Baz", "role": "assistant"},
]
)
```
Before 
After
> Follow up to #1736: correct markup generation for user role messages

- examples/brand/app.py
Reverts [`edbae14` in #1743](https://github.com/posit-dev/py-shiny/pull/1743/commits/edbae14b1b16a60136efa77c06f8425688c7bc26). The color values were hardcoded to allow flipping between branded and default themes.
> fix(brand): Revert change to use hard-coded default colors in example app

- CHANGELOG.md
- pyproject.toml
- shiny/_autoreload.py
See #1766
The websockets package released 14.0 which breaks us when using `shiny run --reload`.
* As @gadenbuie noticed, the [`process_requests` callback has changed](https://websockets.readthedocs.io/en/stable/howto/upgrade.html#arguments-of-serve).
* Even with that fixed (as in this PR's first commit), it prints a scary looking error message: `EOFError: stream ends after 0 bytes, before end of line` and `EOFError: connection closed while reading HTTP request line`. I think this is happening because Shiny's VS Code extension connects via a raw socket just to see if a newly launched Shiny process is listening for requests yet, and if the connection is successful, it immediately closes the connection. The new websockets seems not to like this.
Once we get this working, I think we also need …
> websockets 14.0 support

- tests/pytest/test_chat.py
Gets `pyright` passing on CI.
ollama must not use `pyright` for type checking because `ollama.chat` doesn't have valid `pyright` type hints
https://github.com/ollama/ollama-python/commit/b50a65b27d6c4e5bac42fcf763234e6a4be128b6
> Ignore type error in test introduced by ollama 0.4.2

- CHANGELOG.md
- shiny/ui/_theme.py
- tests/pytest/test_theme.py
Follows the Quarto implementation as described in
https://quarto.org/docs/output-formats/html-themes-more.html#bootstrap-bootswatch-layering.
See also https://rstudio.github.io/sass/reference/sass_layer.html
this method is functionally equivalent to `sass::sass_layer_file()`.
Note that Quarto adds a `uses` layer that we also now support (above `functions` layer), which motivated adding an `.add_uses()` method for completeness.
> feat(Theme): Add `.add_sass_layer_file()` method

- shiny/ui/_chat.py
- tests/playwright/shiny/components/chat/basic/app.py
This way you can get the user input directly from the submit callback rather than the `chat.user_input()` method
```python
from chatlas import ChatAnthropic
chat = ui.Chat(
id="ui_chat",
messages=["Hi! How can I help you today?"],
)
chat.ui()
chat_model = ChatAnthropic()
@chat.on_user_submit
async def handle_user_input(user_input):
response = chat_model.stream(user_input)
await chat.append_message_stream(response)
```
Also, looking forward, a decent way to provide access to uploaded files/images might be through additional function parameters?
> feat(Chat): A `.on_user_submit` callback can now access user input through a function parameter

- examples/brand/app.py
- shiny/ui/_theme_brand.py
- shiny/www/py-shiny/brand/_brand-yml.scss
- shiny/www/shared/sass/bslib/lib/bs5/scss/_variables.scss
- tests/pytest/test_theme.py
The main goal is to move as much Sass code and logic out of Python and into a single `_brand-yml.scss` layer file, building on #1790.
There's a small amount of code insertion that still needs to happen, these places are marked in the Sass file with special comments, e.g. 
```scss
/*-- scss:defaults --*/
/*-- insert(brand.color.palette:defaults) --*/
/*-- insert(brand.defaults:defaults) --*/
/*-- insert(brand.color:defaults) --*/
/*-- insert(brand.typography:defaults) --*/
```
As part of this, we now push a set of brand-specific Sass variables and primarily use these to set other values, e.g. 
```scss
$brand_typography_base_family: Open Sans !default; // optional, added if brand.typography.base.family is present
// ... later ...
$brand_typography_base_family: null !default; // always …
```
> refactor: Move `ui.Theme.from_brand()` Sass code into an `.scss` file

- shiny/playwright/controller/_input_buttons.py
This pull request includes changes to the `shiny/playwright/controller/_input_buttons.py` file to improve functionality and maintainability. The most important changes focus on enhancing the `expect_disabled` method and updating imports.
This was done to handle the case when the `InputActionButton` could have `disabled` attribute or `disabled="disabled"` attribute for the button based on the browser.
* [`shiny/playwright/controller/_input_buttons.py`](diffhunk://#diff-8b40dcca02fe62957e4ce3693ab34cef43fa510088b61ca71cd9b20d192afbc6L64-R65): Modified the `expect_disabled` method to use a regular expression for checking the "disabled" attribute, improving the flexibility of the disabled state check.
> fix(controllers): use regex pattern that matches any string (including an empty string)

- shiny/_app.py
- shiny/_utils.py
- shiny/express/_module.py
- shiny/express/_output.py
- shiny/express/_recall_context.py
- shiny/module.py
- shiny/reactive/_extended_task.py
- shiny/ui/_markdown.py
- tests/pytest/test_navs.py
Black _just_ did a release, this simply runs `black .` on the codebase
> Run black (fix CI)

- .github/workflows/pytest.yaml
This pull request includes a small change to the `.github/workflows/pytest.yaml` file. The change updates the `runs-on` parameter to use the latest version of Ubuntu.
This is because of the deprecation warning in the console as announced in [this issue](https://github.com/actions/runner-images/issues/11101).
* [`.github/workflows/pytest.yaml`](diffhunk://#diff-038d392b404f94b2ee8e3f10b6ae76784160379d9e90638f78ee65df63353221L157-R157): Changed `runs-on` from `ubuntu-20.04` to `ubuntu-latest` for the `playwright-examples` job.
> fix: Change ubuntu tag to use latest

- docs/_quartodoc-testing.yml
Currently the [testing function reference](https://shiny.posit.co/py/api/testing/) page does not include `InputActionButton`.
This pull request includes a minor update to the `docs/_quartodoc-testing.yml` file. The change adds a new entry to the list of contents under the "UI Inputs" section.
Documentation update:
* [`docs/_quartodoc-testing.yml`](diffhunk://#diff-823fd3afe3a93f28487c37be22a0780e7ccf829e8761b5a7594b50a3f8abd6cfR27): Added `playwright.controller.InputActionButton` to the list of contents under the "UI Inputs" section.
> docs: Add missing InputActionButton to testing docs

- shiny/templates/chat/starters/hello/app-express.py
Follow up to #1872 where in the last commit (d3f4c93a1d8d61856048ed2d85846a78db99388b) I committed some changes by mistake 🤦
> Undo unwanted changes to starter template

- CHANGELOG.md
- shiny/ui/_chat.py
- tests/playwright/shiny/components/chat/stream-result/app.py
- tests/playwright/shiny/components/chat/stream-result/test_chat_stream_result.py
Follow up to #1846
Coming back to write about this, I changed my mind about  `get_latest_stream_result()`. Having a more general `.get_message_stream()` is better, especially once I realized returning a "mock" `ExtendedTask` could get rid of some of the `None`/`req(False)` awkwardness.
Here's that same example from #1846 with the new API. It also adds status reporting and cancelling
```python
import asyncio
from shiny import reactive
from shiny.express import input, render, ui
ui.input_action_button("cancel", "Cancel stream")
chat = ui.Chat("chat")
chat.ui()
chat.update_user_input(value="Press Enter to start the stream")
async def stream_generator():
for i in range(10):
await asyncio.sleep(0.25)
yield f"Message {i} \n\n"
@chat.on_user_submit
async def _(message: str):
await …
```
> Replace `.get_latest_stream_result()` with a more general `.get_message_stream()`

- shiny/ui/_navs.py
Brings the documentation from https://rstudio.github.io/bslib/reference/navbar_options.html#navbar-style-with-bootstrap-and-bootswatch-themes to py-shiny
> docs(navbar_options): Describe how to set navbar styles to match Bootswatch themes

- CHANGELOG.md
- shiny/ui/_markdown_stream.py
Follow up to #1880.
In the course of changing the API for `Chat()`, I forgot to make a similar change for `ui.MarkdownStream()` 🤦
> Add `.latest_stream` to `ui.MarkdownStream()` and deprecate `.get_latest_stream_result()`

- shiny/render/_data_frame_utils/_tbl_data.py
- shiny/render/_data_frame_utils/_types.py
[Narwhals#2113](https://github.com/narwhals-dev/narwhals/pull/2113) is going to introduce `Time` dtype, this PR prepares for that by serializing `Time` to `"time"`
> chore: Add support for Narwhals `Time` dtype in `serialize_dtype`

- CHANGELOG.md
- shiny/express/_run.py
- tests/playwright/shiny/components/chat/icon/app.py
These parameters are independent and will not scale with new additions: ex: `bookmark_store`.
Making them kwargs feels like a natural setup.
> chore!: Make `app_opts()` args into kwargs

- shiny/express/_stub_session.py
- shiny/render/_render.py
- shiny/session/_session.py
- shiny/session/_utils.py
- shiny/ui/_chat.py
- shiny/ui/_download_button.py
- shiny/ui/_input_action_button.py
- shiny/ui/_input_check_radio.py
- shiny/ui/_input_dark_mode.py
- shiny/ui/_input_date.py
- shiny/ui/_input_file.py
- shiny/ui/_input_numeric.py
- shiny/ui/_input_password.py
- shiny/ui/_input_select.py
- shiny/ui/_input_slider.py
- shiny/ui/_input_task_button.py
- shiny/ui/_input_text.py
- shiny/ui/_input_update.py
- shiny/ui/_markdown_stream.py
- shiny/ui/_output.py
- shiny/ui/_sidebar.py
- shiny/ui/dataframe/_data_frame.py
- tests/pytest/test_chat.py
- tests/pytest/test_modules.py
- tests/pytest/test_namespaces.py
- tests/pytest/test_output_transformer.py
- tests/pytest/test_render_data_frame.py
- tests/pytest/test_render_data_frame_tbl_data.py
Updated:
* `shiny._namespaces_.resolve_id()` -> `shiny.module.resolve_id()`
* `shiny._namespaces_.current_namespace()` -> `shiny.module.current_namespace()`
* `shiny._namespaces_.ResolvedId` -> `shiny.module.ResolvedId`
Related: #1896
> chore: Use `shiny.module` to import reexported values from `shiny._namespaces`

- shiny/_launchbrowser.py
- shiny/_main.py
Ex: `SHINY_PORT` is set by hosted environments and is inspected to determine if an app is being hosted. 
Related: https://github.com/rstudio/shiny/blob/f55c26af4a0493b082d2967aca6d36b90795adf1/R/server.R#L510-L514
Useful for bookmarking to determine it's own `inShinyServer()` method
> chore: Rename temp environ names to avoid conflict with local names

- shiny/session/_utils.py
- shiny/ui/_chat.py
- shiny/ui/_chat_normalize.py
- shiny/ui/_chat_provider_types.py
- shiny/ui/_chat_types.py
- tests/pytest/test_chat.py
Addresses https://github.com/posit-dev/py-shiny/pull/1868#discussion_r1983741748
Note also this branches off of https://github.com/posit-dev/py-shiny/pull/1868
> fix(Chat)!: Move away from inheriting from TypedDict for internal Chat classes

- shiny/bookmark/README.md
- shiny/bookmark/__init__.py
- shiny/bookmark/_bookmark.py
- shiny/bookmark/_save_state.py
- shiny/bookmark/_serializers.py
- shiny/input_handler.py
> docs(bookmark): Add technical doc

- shiny/bookmark/_bookmark.py
> feat(bookmarking): Add `await session.bookmark.get_bookmark_url()`

- tests/pytest/test_shiny_import.py
VSCode likes to import from the shiny module itself within the shiny package. While it works... it relies on import magic, not relative imports.
Bad: `from shiny import foo`
Bad: `from shiny.foo import bar`
Bad: `import shiny`
Good: `from . import foo`
Good: `from .foo import bar`
> chore: Add test to verify shiny isn't importing itself internally

- CHANGELOG.md
- shiny/session/_session.py
- tests/playwright/shiny/bookmark/modules/test_bookmark_modules.py
Before the PR, `SessionProxy`'s `make_scope(id)` would recursively call up the chain to `.make_scope(id)`. This would hit the root `AppSession` and call make scope with resolved namespace `id`. However, this set's the `._parent` value of the Proxy session to `Root` and not the calling session. Ex: A nested module `A-B-C`'s parent session currently is the root session, `""`, not a proxy session with namespace `A-B`.
This worked as we would use `self._ns` (properly resolved) instead of `self._parent._ns` when needing to construct any namespace values. Since the namespace values is all that we _really_ need and all recursive functions didn't add any intermediate proxy logic, it happen to work until now.
While debugging bookmark handlers, I noticed that the `session.bookmark.on_bookmark` …
> fix(session): Always have calling session be the parent session when making a scoped session

- CHANGELOG.md
- shiny/session/_session.py
- tests/playwright/shiny/bookmark/modules/test_bookmark_modules.py
This reverts commit 14b92d4e8f273560ba63a9c4e1206a7f4b0aa9e1 via #1923
From conversations with @jcheng5 , the proxy sessions should have a single "parent" object which is "Root" session, they should not recurse up the session family tree during calls. 
In a followup PR, I'll rename `._parent` to `._root_session` to avoid confusion.
From chat w/ @jcheng5 
> If there are reasons we want nested session scopes to actually be related (and there are reasons we might--like we could add `.destroy()` methods that recursively kill their child scopes), we can do that, but we’d have to make further changes I think. 
> 
> Off the top of my head, we’d have to make sure that make_scope:
> 1. Always returns the same object when `make_scope` is passed with the same `id`, much like Python does with loaded …
> fix: Revert - fix(session): Always have calling session be the parent session when making scoped session

- shiny/bookmark/_bookmark.py
- shiny/express/_stub_session.py
- shiny/session/_session.py
Related: https://github.com/posit-dev/py-shiny/pull/1924#issue-2925895036
Also apply to `Bookmark` classes
> chore(session): Rename `._parent` to `._root_session` in `Session` classes

- shiny/ui/_markdown_stream.py
- tests/playwright/shiny/components/MarkdownStream/stream-result/app.py
- tests/playwright/shiny/components/MarkdownStream/stream-result/test_latest_stream_result.py
Follow up to https://github.com/posit-dev/py-shiny/pull/1880.
> fix(MarkdownStream): correctly set the latest stream when it gets invoked

- shiny/bookmark/_bookmark.py
Default the `url=` to current bookmark url
> feat(bookmark): Allow for `session.bookmark.update_query_string(query_string=)` to be optional

- shiny/ui/_chat_normalize.py
This PR makes two small changes:
1. Fixes the incorrect error message that directs users to a non-existent function path for registering custom normalizers
2. Adds a new `register_custom_normalizer` function with documentation and examples
Fixes #1935
> Add register_custom_normalizer function and fix error message

- shiny/ui/_chat.py
- tests/playwright/shiny/components/chat/icon/app.py
Follow up to #1853
Apparently statically rendered custom icons were never working as intended. Here's an example:
```python
import faicons
welcome = """
**Hello!** How can I help you today?
Here are a couple suggestions:
* <span class="suggestion">Tell me a joke</span>
* <span class="suggestion submit">Tell me a story</span>
"""
ui.br()
chat = ui.Chat(id="chat")
chat.ui(
messages=[welcome],
icon_assistant=faicons.icon_svg("otter"),
)
```
Currently, you get the default robot icon, when you should get an otter in the startup message.
This got overlooked because `ui.Chat()`'s `messages` are dynamically rendered (and thus, are included in the server-side state), but `.ui(messages)` is static (and thus is not)
> fix(Chat): fix statically rendered custom icons

- CHANGELOG.md
- shiny/ui/_navs.py
- tests/playwright/shiny/components/nav/navset_bar_options/app.py
- tests/playwright/shiny/components/nav/navset_bar_options/test_navset_bar_options.py
- tests/pytest/test_navs.py
Fixes #1941 to correctly pass `navbar_options.attrs` to the navbar container, as well as setting the `data-bs-theme` attribute. This was an oversight in #1822 and should have been included there.
> fix(navbar_options): Apply attributes and `theme`

- MANIFEST.in
- pyproject.toml
- shiny/_main.py
- shiny/bookmark/_bookmark_state.py
- shiny/bookmark/_serializers.py
- shiny/input_handler.py
- shiny/session/_session.py
- shiny/ui/_input_file.py
- tests/playwright/ai_generated_apps/bookmark/input_file/app-express.py
- tests/playwright/ai_generated_apps/bookmark/input_file/test_input_file_express_bookmarking.py
> feat(bookmark): Support bookmarking input files

- pyproject.toml
- shiny/_main.py
- shiny/api-examples/notification_show/app-core.py
- shiny/api-examples/notification_show/app-express.py
- shiny/bookmark/_bookmark.py
- tests/pytest/test_reactives.py
With https://github.com/encode/uvicorn/pull/2602, the expected behavior is achieved and this PR's changes in `_main.py` may be reverted.
---------------------------
We are close to a release and can not have a uv source in the `pyproject.toml`. Therefore, we're removing it and extending the reload-excludes to exclude any file within  `shiny_bookmarks` up to 5 sub-folders deep. This should be a near 100% coverage.
> chore(uvicorn): Remove uv source of uvicorn PR

- CHANGELOG.md
- shiny/_app.py
- shiny/bookmark/_global.py
- shiny/bookmark/_restore_state.py
- shiny/bookmark/_save_state.py
Related to Connect, shinylive, SSO/SSP integration
> fix(bookmarking): Be able to set the default save/restore functions after `app` initialization

- tests/playwright/shiny/bookmark/chat/client_state/test_bookmark_chat.py
This pull request includes a change to the `tests/playwright/shiny/bookmark/chat/client_state/test_bookmark_chat.py` file to improve the stability of the test. The change involves marking the `test_bookmark_chat` function as flaky and allowing it to rerun up to three times with a one-second delay between reruns.
> test(bookmark): Add retries to flaky test

- tests/playwright/shiny/components/nav/navsets_kitchensink/test_navsets_kitchensink.py
Improvements to test reliability:
* Added `pytest` import to enable the use of `pytest.mark.flaky` for retrying flaky tests.
* Annotated the `test_navset_kitchensink` function with `@pytest.mark.flaky` to allow up to 5 retries with a 1-second delay between attempts, addressing intermittent WebKit timing issues.
> test(navset): Add retries to flaky navset test for intermittent webkit failures

- .github/workflows/deploy-tests.yaml
This pull request updates the deployment configuration in the `.github/workflows/deploy-tests.yaml` file to use a new server URL for dogfood Connect server environments.
> test(deploys): Switch urls to new dogfood server

- CHANGELOG.md
- shiny/bookmark/_bookmark.py
When showing the notification during bookmarking, sometimes the session was unknown. 
By always supplying the session, the error goes away.
> fix(bookmarking): Fix unknown session when displaying error

- CHANGELOG.md
- shiny/bookmark/_button.py
> docs: Explicitly call out module usage in bookmark button

- Makefile
- tests/playwright/shiny/components/chat/shiny_output/app.py
- tests/playwright/shiny/components/data_frame/edit/app.py
- tests/playwright/shiny/components/data_frame/html_columns/app.py
This pull request includes updates to improve type-checking annotations and resolve `pyright` warnings in various test files. The changes primarily focus on adding or modifying `pyright` ignore comments to address type-related issues, as well as minor code formatting adjustments for clarity.
> fix(typing): add pyright: ignore to plotly functions within apps

- tests/playwright/shiny/components/MarkdownStream/basic/test_stream_basic.py
Issue:
Some tests are timing out on GHA machines.
Fix: Expand how long we wait for these tests to complete.
> fix: Expanding timeout test

- docs/_quartodoc-testing.yml
- shiny/playwright/controller/_output.py
- tests/playwright/shiny/components/data_frame/validate_row_selection_edit_mode/test_validate_row_selection_edit_mode.py
- tests/pytest/test_controller_documentation.py
The key changes include enhancements to the documentation configuration, updates to test coverage, and improvements to method implementations for better functionality and maintainability.
* Added new controllers `InputBookmarkButton` and `PageNavbar` to the documentation configuration in `docs/_quartodoc-testing.yml`. This ensures these controllers are now included in the generated documentation.
* Updated the `expect_class_state` method in `shiny/playwright/controller/_output.py` to consistently include the `timeout` parameter in all `expect_cell_class` calls, improving flexibility and consistency.
* Added assertions in `test_validate_row_selection_in_edit_mode` to ensure proper row focus and cell state after exiting edit mode, improving the robustness of the test.
* Introduced a new …
> test(controller): Add test for controller documentation coverage

- tests/playwright/examples/example_apps.py
Deleted two deprecated warning messages related to DatetimeIndex.format and Series.__getitem__ from the app_allow_external_errors list in example_apps.py. These warnings are no longer needed for error allowance.
This is possible because of [this PR](https://github.com/posit-dev/py-shiny-templates/pull/39)
> fix(example-tests): Remove deprecated warning messages from allowed errors

- tests/playwright/shiny/components/data_frame/validate_row_selection_edit_mode/test_validate_row_selection_edit_mode.py
Inserted assertions to verify row focus state before and after pressing Escape in the data frame edit mode validation test. This enables dynamic delays between rapid, successive key presses.
> fix(test): Add row focus state checks in edit mode test

- CHANGELOG.md
- shiny/playwright/controller/_navs.py
- tests/playwright/shiny/components/nav/navset_menu/app-express.py
- tests/playwright/shiny/components/nav/navset_menu/test_app.py
This pull request enhances navigation handling for dropdown menus in the navigation panel and adds comprehensive Playwright tests for these scenarios. The most important changes include improving the logic for clicking navigation items inside dropdowns and introducing new test applications and test cases to ensure correct behavior for both pill and underline navigation sets.
**Navigation logic improvements:**
* Improved the `click` method in `shiny/playwright/controller/_navs.py` to detect when a navigation panel is inside a closed dropdown menu and automatically open the dropdown before clicking the target item. This ensures reliable navigation interaction in dropdown scenarios.
**Testing enhancements:**
* Added a new test application `app-express.py` under …
> fix(test): Add ability to select `ui.nav_menu` controllers

- shiny/module.py
incorporated the text from #705 and #1974 to improve on the module server and ui docstrings.
closes #705
> docs: update module server and ui to incorporate #705

- Makefile
- pyproject.toml
- shiny/pytest/_generate/_main.py
This pull request updates the testing dependencies and configuration for the project, primarily by renaming and expanding the test dependency group and correcting a model name in the test generation code. The most important changes are:
* Renamed the `testgen` dependency group to `add-test` in `pyproject.toml` and expanded it to include `pytest`, `pytest-playwright`, and `playwright` for improved test capabilities.
* Updated the `Makefile` to use the new `add-test` dependency group instead of the old `testgen` group for installing test dependencies.
* Fixed the default OpenAI model name in `shiny/pytest/_generate/_main.py` from `gpt-5-mini-2025-08-07` to `gpt-5-2025-08-07` to ensure correct model usage.
> chore(add-test): Rename testgen extra to add-test and update Makefile

- pytest.ini
- tests/playwright/shiny/components/chat/stream-result/test_chat_stream_result.py
This pull request makes a minor configuration change to the `pytest.ini` file, adjusting the scope of the default asyncio fixture loop from `fixture` to `function`. This change ensures that a new event loop is created for each test function, which can help prevent cross-test interference in asynchronous test scenarios.
This [change](https://github.com/pytest-dev/pytest-asyncio/pull/1189) is causing pytest tests to fail since `fixture` is not a valid value anymore
Also make the `test_chat_stream_result` test more robust
> fix(asyncio-test): fixture is no longer a valid value for asyncio
